{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtSl2_spr_hearts",
  "bbox_bottom": 269,
  "bbox_left": 0,
  "bbox_right": 479,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c1fad6cc-1a5a-431d-8dbd-dc6d18bb05fc",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"63952006-0091-4751-98eb-118b0b1af54f",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"60608288-0306-4fb8-810b-e72b4f311bd8",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a64386fb-ea3c-42f7-9624-7d4017ea3b71",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"4b1cba54-1390-4834-8824-0f52bd9a2d0c","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtSl2_spr_hearts",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c1fad6cc-1a5a-431d-8dbd-dc6d18bb05fc","path":"sprites/ibtSl2_spr_hearts/ibtSl2_spr_hearts.yy",},},},"Disabled":false,"id":"485cb544-a1b1-4065-980e-17d2e034f8c2","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"63952006-0091-4751-98eb-118b0b1af54f","path":"sprites/ibtSl2_spr_hearts/ibtSl2_spr_hearts.yy",},},},"Disabled":false,"id":"397fd6cb-0ff1-4260-a3be-6d06cc8f2068","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"60608288-0306-4fb8-810b-e72b4f311bd8","path":"sprites/ibtSl2_spr_hearts/ibtSl2_spr_hearts.yy",},},},"Disabled":false,"id":"59a8e3b4-379d-44a1-90de-b3943161f6ea","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a64386fb-ea3c-42f7-9624-7d4017ea3b71","path":"sprites/ibtSl2_spr_hearts/ibtSl2_spr_hearts.yy",},},},"Disabled":false,"id":"b2c0ccf0-e1e3-4372-a067-bcd642f424b8","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}