event_inherited();
anim_init();
scr_player_load_sprites(!global.char);
anim_play(anim_idle);
facing = 1;
hspd = 0;
vspd = 0;
zspd = 0;
grounded = true;
dir = 270;
z = 0;
zprevious = z;
z_view = 0;
scr_player_actions_init();
swap_x = x;
swap_y = y;
swap_z = z;
scr_create_shadow();
height = 128;
draw_me = true;
running = false;
