{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_leaderboard_tabbtn_local",
  "bbox_bottom": 11,
  "bbox_left": 0,
  "bbox_right": 28,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b5208976-c45c-4b02-8a79-3bee9df2a053",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c7d03861-e352-4077-a73b-5a059a5dc2f8",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 12,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"a021f01e-96f4-4c34-af6a-ffd7d7e7f310","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": {
    "resourceType": "GMNineSliceData",
    "resourceVersion": "1.0",
    "bottom": 1,
    "enabled": true,
    "guideColour": [
      4294902015,
      4294902015,
      4294902015,
      4294902015,
      4294902015,
    ],
    "highlightColour": 1728023040,
    "highlightStyle": 0,
    "left": 4,
    "right": 4,
    "tileMode": [
      0,
      0,
      0,
      0,
      0,
    ],
    "top": 1,
  },
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_leaderboard_tabbtn_local",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 2.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b5208976-c45c-4b02-8a79-3bee9df2a053","path":"sprites/spr_leaderboard_tabbtn_local/spr_leaderboard_tabbtn_local.yy",},},},"Disabled":false,"id":"593dddd8-58af-4a7e-b4f5-7afdf0466ec1","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c7d03861-e352-4077-a73b-5a059a5dc2f8","path":"sprites/spr_leaderboard_tabbtn_local/spr_leaderboard_tabbtn_local.yy",},},},"Disabled":false,"id":"a590e52a-fff1-44ee-ab26-de61e662c162","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 29,
}