{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_pandorathoughts_lit",
  "bbox_bottom": 349,
  "bbox_left": 214,
  "bbox_right": 479,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5b76db1b-7747-4400-a31b-48ab2f04964b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"3c34045d-2db9-4da5-9604-7213c9fcd499",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b8a2dcbe-2e3d-4986-a8d8-c041e9f55758",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6bf4830b-549f-43d1-beef-10dbf428175a",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 350,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"18b3eeef-f6b6-4dde-8ab7-2c3ce2b3dd9f","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 2,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_pandorathoughts_lit",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 3.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5b76db1b-7747-4400-a31b-48ab2f04964b","path":"sprites/spr_pandorathoughts_lit/spr_pandorathoughts_lit.yy",},},},"Disabled":false,"id":"245ef7e7-e353-468b-9e0f-97621019c75d","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"3c34045d-2db9-4da5-9604-7213c9fcd499","path":"sprites/spr_pandorathoughts_lit/spr_pandorathoughts_lit.yy",},},},"Disabled":false,"id":"404ce33c-661e-40f5-bc4a-b7628b770e61","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b8a2dcbe-2e3d-4986-a8d8-c041e9f55758","path":"sprites/spr_pandorathoughts_lit/spr_pandorathoughts_lit.yy",},},},"Disabled":false,"id":"b2a4f4f7-93a7-4395-a8de-4bfdf2be6662","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6bf4830b-549f-43d1-beef-10dbf428175a","path":"sprites/spr_pandorathoughts_lit/spr_pandorathoughts_lit.yy",},},},"Disabled":false,"id":"9000a1c4-2b9f-4af9-9689-567fd306406d","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 480,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}