{
  "resourceType": "GMSequence",
  "resourceVersion": "1.4",
  "name": "sqcs_0_0intro",
  "autoRecord": true,
  "backdropHeight": 768,
  "backdropImageOpacity": 0.5,
  "backdropImagePath": "",
  "backdropWidth": 1366,
  "backdropXOffset": 0.0,
  "backdropYOffset": 0.0,
  "events": {
    "resourceType": "KeyframeStore<MessageEventKeyframe>",
    "resourceVersion": "1.0",
    "Keyframes": [],
  },
  "eventStubScript": null,
  "eventToFunction": {},
  "length": 3244.0,
  "lockOrigin": false,
  "moments": {
    "resourceType": "KeyframeStore<MomentsEventKeyframe>",
    "resourceVersion": "1.0",
    "Keyframes": [
      {"resourceType":"Keyframe<MomentsEventKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"MomentsEventKeyframe","resourceVersion":"1.0","Events":[],},},"Disabled":false,"id":"b1c0a393-472a-4f4b-a0a6-0d5fe4a13c8a","IsCreationKey":false,"Key":2882.0,"Length":1.0,"Stretch":false,},
      {"resourceType":"Keyframe<MomentsEventKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"MomentsEventKeyframe","resourceVersion":"1.0","Events":[],},},"Disabled":false,"id":"469d314c-a50d-4db3-9667-9a276d8ddffe","IsCreationKey":false,"Key":3240.0,"Length":1.0,"Stretch":false,},
    ],
  },
  "parent": {
    "name": "Sequences",
    "path": "folders/Sequences.yy",
  },
  "playback": 0,
  "playbackSpeed": 60.0,
  "playbackSpeedType": 0,
  "showBackdrop": true,
  "showBackdropImage": false,
  "spriteId": null,
  "timeUnits": 1,
  "tracks": [
    {"resourceType":"GMAudioTrack","resourceVersion":"1.1","name":"SFX","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AudioKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AudioKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AudioKeyframe","resourceVersion":"1.0","Id":{"name":"cs_0_0_sfx_1","path":"sounds/cs_0_0_sfx_1/cs_0_0_sfx_1.yy",},"Mode":0,},},"Disabled":false,"id":"698f14d6-c00a-405e-bcb3-0946c34bb32f","IsCreationKey":false,"Key":-43.0,"Length":3104.9126,"Stretch":false,},
        ],},"modifiers":[],"trackColour":8421376,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"18753628-b71d-46ba-a338-3f064dc9703d","IsCreationKey":false,"Key":-43.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421376,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"3e6a2609-0e74-4bdf-ba49-daf63e30c444","IsCreationKey":false,"Key":-43.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421376,"tracks":[],"traits":0,},
      ],"traits":0,},
    {"resourceType":"GMAudioTrack","resourceVersion":"1.1","name":"MUSIC","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AudioKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AudioKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AudioKeyframe","resourceVersion":"1.0","Id":{"name":"cs_0_0_music_1","path":"sounds/cs_0_0_music_1/cs_0_0_music_1.yy",},"Mode":0,},},"Disabled":false,"id":"73065ec3-9115-4693-ab94-bb8e7133b73b","IsCreationKey":false,"Key":-45.0,"Length":3104.9126,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4286611584,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"47c63e3c-b79a-46a7-b3f8-570c30c5d4ec","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4286611584,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"0bfd732e-a39a-402f-8fe8-32be1387c42a","IsCreationKey":false,"Key":-45.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4286611584,"tracks":[],"traits":0,},
      ],"traits":0,},
    {"resourceType":"GMAudioTrack","resourceVersion":"1.1","name":"MUSIC_HIDE_ME","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AudioKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AudioKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AudioKeyframe","resourceVersion":"1.0","Id":{"name":"mus_mainmenu_1","path":"sounds/mus_mainmenu_1/mus_mainmenu_1.yy",},"Mode":0,},},"Disabled":false,"id":"274af2f3-1e54-42fb-919e-da3d9c26f2c5","IsCreationKey":false,"Key":2882.0,"Length":366.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4278190208,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-240.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"1f25bf05-bc90-4695-99ed-6ee89e019364","IsCreationKey":false,"Key":2935.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190208,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"47d11225-ef5b-4e2a-b6d4-4e8d9d912e89","IsCreationKey":false,"Key":2882.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190208,"tracks":[],"traits":0,},
      ],"traits":0,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_0","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_0_1","path":"sequences/sqcs_0_0_0_1/sqcs_0_0_0_1.yy",},},},"Disabled":false,"id":"8a8c91e9-af23-46ec-be43-409378a35731","IsCreationKey":false,"Key":56.0,"Length":211.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4290822336,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"14fa3134-cef4-49b5-9e33-219f133ca662","IsCreationKey":false,"Key":56.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4290822336,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"c6001a35-2ba3-4b39-b8ed-15e8e1a758c5","IsCreationKey":false,"Key":56.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4290822336,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"f7c3207a-6d90-4a10-b1ee-5ee8a30a2ddd","IsCreationKey":false,"Key":56.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4290822336,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"e99bb003-a98c-4d97-9251-43211fe23624","IsCreationKey":false,"Key":56.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4290822336,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_1","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_1_1","path":"sequences/sqcs_0_0_1_1/sqcs_0_0_1_1.yy",},},},"Disabled":false,"id":"0e1ee5a6-c59d-4fa7-b8d0-af8aafaf8900","IsCreationKey":false,"Key":266.0,"Length":186.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":8421504,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"cbc556f7-9ed5-482d-95a1-2aa32d49d18d","IsCreationKey":false,"Key":266.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421504,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"7da611de-5ccb-4d33-88e9-b29ce7469760","IsCreationKey":false,"Key":266.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421504,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"ce05a60b-1cbe-403c-a40c-acc584b7837e","IsCreationKey":false,"Key":266.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421504,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"91f50759-cd9c-4f9b-8efd-65b5fa80f216","IsCreationKey":false,"Key":266.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":8421504,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_2","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_2_1","path":"sequences/sqcs_0_0_2_1/sqcs_0_0_2_1.yy",},},},"Disabled":false,"id":"8e65f12b-f070-4283-9f7a-b25c2ed3b175","IsCreationKey":false,"Key":451.0,"Length":141.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294901760,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"c68af70e-1c4c-4c50-8df9-89344e12385f","IsCreationKey":false,"Key":451.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"6097037b-b4d4-4c18-acd3-80fc7c268b70","IsCreationKey":false,"Key":451.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"958726bd-01f0-43fc-96a7-6ee10d53e2c0","IsCreationKey":false,"Key":451.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"0bf87c9a-9cf5-4be2-9331-05e187a74bcb","IsCreationKey":false,"Key":451.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_3","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_3_1","path":"sequences/sqcs_0_0_3_1/sqcs_0_0_3_1.yy",},},},"Disabled":false,"id":"d0db7d0f-025e-4bca-b881-062787a7e6a5","IsCreationKey":false,"Key":591.0,"Length":305.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294967040,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"8b97c678-0f3e-49e7-b0bb-c8c9b8a4a980","IsCreationKey":false,"Key":591.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"8705da5e-f31e-4b5a-9018-9f4ecc540cc4","IsCreationKey":false,"Key":591.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"517539e8-54a1-4be5-92cd-4d48a1e92e78","IsCreationKey":false,"Key":591.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"1d6ffc3c-dad4-487f-8e2d-b8877923af76","IsCreationKey":false,"Key":591.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_4","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_4_1","path":"sequences/sqcs_0_0_4_1/sqcs_0_0_4_1.yy",},},},"Disabled":false,"id":"01a4649e-6367-46cd-b800-2e15f08fbfd6","IsCreationKey":false,"Key":895.0,"Length":309.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294901760,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"4ce9e616-b408-476e-b7b6-1ba38d63ecd0","IsCreationKey":false,"Key":895.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"59e1d716-571c-4cdd-ad88-7cb20ccb77a2","IsCreationKey":false,"Key":895.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"cebe1182-5665-4fa4-9d31-9fe06471e0eb","IsCreationKey":false,"Key":895.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"949267d7-56ae-4a42-a151-889fd4037487","IsCreationKey":false,"Key":895.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294901760,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_5","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_5_1","path":"sequences/sqcs_0_0_5_1/sqcs_0_0_5_1.yy",},},},"Disabled":false,"id":"35e9d932-cff1-4bda-bbb0-48200a38e285","IsCreationKey":false,"Key":1203.0,"Length":150.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294967040,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"2eb47382-c0ca-431f-8423-281a87184501","IsCreationKey":false,"Key":1203.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"98ddada6-21aa-456e-b09a-63eedee0e92b","IsCreationKey":false,"Key":1203.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"d3ef5b83-6cdd-4452-98a2-e7b421213515","IsCreationKey":false,"Key":1203.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"83a80bae-f62e-4b32-9a3f-eb4e1a55c833","IsCreationKey":false,"Key":1203.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_6","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_6_1","path":"sequences/sqcs_0_0_6_1/sqcs_0_0_6_1.yy",},},},"Disabled":false,"id":"29abda44-fd1a-4ff6-b210-63c4cd0157b6","IsCreationKey":false,"Key":1352.0,"Length":485.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294902015,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"b57010f6-fad6-473a-830b-a131a3f67ace","IsCreationKey":false,"Key":1352.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294902015,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"e1db5f87-173d-4ca1-8e0f-f6c9d6644db0","IsCreationKey":false,"Key":1352.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294902015,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"b0720938-9fd8-4dda-9cab-9900366ee384","IsCreationKey":false,"Key":1352.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294902015,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"27ad76b5-b90a-445f-bdfa-56901dca382e","IsCreationKey":false,"Key":1352.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294902015,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_7","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_7_1","path":"sequences/sqcs_0_0_7_1/sqcs_0_0_7_1.yy",},},},"Disabled":false,"id":"a68c64b9-fe4b-4ec4-8f83-9693ab5f398b","IsCreationKey":false,"Key":1834.0,"Length":167.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":12632256,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"1d814280-aa79-496f-8cf3-854e506d31b4","IsCreationKey":false,"Key":1834.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":12632256,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"fb846b69-e4db-46b9-ab6b-9587bd8bcf7b","IsCreationKey":false,"Key":1834.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":12632256,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"e35ae134-6e64-425d-b989-178bef68d7d3","IsCreationKey":false,"Key":1834.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":12632256,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"2a774170-35af-4d35-a4f6-569e572fca7f","IsCreationKey":false,"Key":1834.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":12632256,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_8","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_8_1","path":"sequences/sqcs_0_0_8_1/sqcs_0_0_8_1.yy",},},},"Disabled":false,"id":"e8db7ae3-24b4-447a-902d-fb3245f51079","IsCreationKey":false,"Key":2000.0,"Length":321.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4278190080,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"e3c2db77-ab7f-46d4-a5c4-e74b80708910","IsCreationKey":false,"Key":2000.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190080,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"c28f1dd3-84d6-456c-a5e4-fe60d75bfe30","IsCreationKey":false,"Key":2000.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190080,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"370ed153-4c4e-45cc-849b-fc1e846cd6a9","IsCreationKey":false,"Key":2000.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190080,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"3e1dfc0a-a30f-488a-b2c5-6608caa4b96c","IsCreationKey":false,"Key":2000.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278190080,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_9","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_9_1","path":"sequences/sqcs_0_0_9_1/sqcs_0_0_9_1.yy",},},},"Disabled":false,"id":"fd1b9ef0-7c67-4116-b83b-f2a96b8f91cb","IsCreationKey":false,"Key":2317.0,"Length":126.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294967040,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"6d268678-0064-485d-b075-f3299e5af802","IsCreationKey":false,"Key":2317.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"0bd6243d-005c-4fac-98ce-86a4ce551a27","IsCreationKey":false,"Key":2317.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"78efccaa-c61d-4404-abaa-f3095910aa00","IsCreationKey":false,"Key":2317.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"e46571d5-4ebc-4bca-8c22-b194a1e17d3a","IsCreationKey":false,"Key":2317.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294967040,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_10","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_10_1","path":"sequences/sqcs_0_0_10_1/sqcs_0_0_10_1.yy",},},},"Disabled":false,"id":"356a4c0d-4749-459a-9635-03118c20b76c","IsCreationKey":false,"Key":2442.0,"Length":182.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":2164260863,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"8c8b6530-7825-4321-862a-8a179eecf7bc","IsCreationKey":false,"Key":2442.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":2164260863,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"ed3fa49a-aa58-430c-a276-65041087dcea","IsCreationKey":false,"Key":2442.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":2164260863,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"e4a3c090-7906-4289-9352-c9c171819051","IsCreationKey":false,"Key":2442.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":2164260863,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"a7087afa-2b7d-480e-b9f0-2e49443d051a","IsCreationKey":false,"Key":2442.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":2164260863,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_11","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_11_1","path":"sequences/sqcs_0_0_11_1/sqcs_0_0_11_1.yy",},},},"Disabled":false,"id":"d3b191ea-3820-4aed-8432-0f07eb75a3c0","IsCreationKey":false,"Key":2621.0,"Length":334.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":128,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"ffb07930-bc35-47ca-873b-69d3a2e3a490","IsCreationKey":false,"Key":2621.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":128,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"a9799ac7-00db-4532-b227-8f94d2f22d96","IsCreationKey":false,"Key":2621.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":128,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"391e8b90-7713-486e-a551-8c112605393a","IsCreationKey":false,"Key":2621.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":128,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"2817b81a-c330-42f4-9bd9-2a2bba52a849","IsCreationKey":false,"Key":2621.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":128,"tracks":[],"traits":0,},
      ],"traits":1,},
    {"resourceType":"GMSequenceTrack","resourceVersion":"1.0","name":"sqcs_0_0_12","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSequenceKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSequenceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSequenceKeyframe","resourceVersion":"1.0","Id":{"name":"sqcs_0_0_12_1","path":"sequences/sqcs_0_0_12_1/sqcs_0_0_12_1.yy",},},},"Disabled":false,"id":"52912c03-ec21-4b9f-9d85-6aed37cc8fa9","IsCreationKey":false,"Key":2953.0,"Length":291.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4294944000,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"0f08d8ed-f534-434c-8a3b-8e783b21f85f","IsCreationKey":false,"Key":2953.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294944000,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"36a59cbe-d97c-4fed-96fc-21d672201df6","IsCreationKey":false,"Key":2953.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294944000,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"5405d5bc-c7f9-4cc3-aa8a-56cb48c6b500","IsCreationKey":false,"Key":2953.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294944000,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"3d63d334-ac99-47fc-baa8-51e4753d4e54","IsCreationKey":false,"Key":2953.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4294944000,"tracks":[],"traits":0,},
      ],"traits":1,},
  ],
  "visibleRange": null,
  "volume": 1.0,
  "xorigin": 0,
  "yorigin": 0,
}