{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms1_spr_ui_apple",
  "bbox_bottom": 31,
  "bbox_left": 3,
  "bbox_right": 31,
  "bbox_top": 3,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"03be41fe-6c5a-492d-8720-083ae004c804",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f28ec78a-665a-4ddb-95f8-4c6e6b2a4b3e",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5ee0022f-6910-478e-9383-82d11ccf1bf9",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 35,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"f4c81f36-ab37-421d-a165-659328cffc13","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms1_spr_ui_apple",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"03be41fe-6c5a-492d-8720-083ae004c804","path":"sprites/ms1_spr_ui_apple/ms1_spr_ui_apple.yy",},},},"Disabled":false,"id":"763372d8-2fdc-41a2-ab37-bec9c9accc02","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f28ec78a-665a-4ddb-95f8-4c6e6b2a4b3e","path":"sprites/ms1_spr_ui_apple/ms1_spr_ui_apple.yy",},},},"Disabled":false,"id":"c3484f5a-6c69-48fc-a146-374ac22ff4d0","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5ee0022f-6910-478e-9383-82d11ccf1bf9","path":"sprites/ms1_spr_ui_apple/ms1_spr_ui_apple.yy",},},},"Disabled":false,"id":"dab4240b-772c-40a9-aa30-e9aef20e0fb8","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 17,
    "yorigin": 17,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 35,
}