{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtG_spr_life_sad",
  "bbox_bottom": 55,
  "bbox_left": 0,
  "bbox_right": 54,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"679b02c8-76ce-46b4-b763-717d2c8b7969",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"ca81db2f-672c-423c-9c6c-107aaa3d9807",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f3776f10-11db-4636-ace4-1b66a1b83745",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2ccad347-9870-49b1-9c13-a4042afea814",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 56,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"95be46cd-c25d-4af1-a86b-ce845a1263e7","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtG_spr_life_sad",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 25.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"679b02c8-76ce-46b4-b763-717d2c8b7969","path":"sprites/ibtG_spr_life_sad/ibtG_spr_life_sad.yy",},},},"Disabled":false,"id":"588f8744-17ea-448d-8118-34983c26df59","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"ca81db2f-672c-423c-9c6c-107aaa3d9807","path":"sprites/ibtG_spr_life_sad/ibtG_spr_life_sad.yy",},},},"Disabled":false,"id":"73187b0f-c478-410a-8477-5303799f219e","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f3776f10-11db-4636-ace4-1b66a1b83745","path":"sprites/ibtG_spr_life_sad/ibtG_spr_life_sad.yy",},},},"Disabled":false,"id":"de428385-b2e4-43cb-9db2-a4a78b8196e2","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2ccad347-9870-49b1-9c13-a4042afea814","path":"sprites/ibtG_spr_life_sad/ibtG_spr_life_sad.yy",},},},"Disabled":false,"id":"41ba3d8f-03a2-4f7b-8740-beeb84a1e16b","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 27,
    "yorigin": 28,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 55,
}