testvariablenothing = false;
event_inherited();
global.hp_spr = spr_trans_hp_boss;
global.hp_spr_lose = spr_trans_hp_boss_lost;
global.frenzy_name = "boss_knives";
global.frenzy_music = bgm_subwayboss_140;
global.frenzy_music_list = [bgm_subwayboss_140, bgm_subwayboss_160, bgm_subwayboss_170];
global.frenzy_music_list_loss = [bgm_subwayboss_loss_140, bgm_subwayboss_loss_160, bgm_subwayboss_loss_170];
macro_textures_fetch = ["tg_macro_knives"];
trans_lose = obj_bosstrans_knives_loss;
var _order0 = obj_bosstrans_knives_lance;
var _order1 = obj_bosstrans_knives_jade;
var _order2 = obj_bosstrans_knives_snake;
var _order3 = obj_bosstrans_knives_dennis;
trans_order[0] = obj_bosstrans_knives_opening;
trans_order[1] = _order0;
trans_order[2] = _order1;
trans_order[3] = _order2;
trans_order[4] = _order3;
trans_order[5] = _order0;
trans_order[6] = _order1;
trans_order[7] = obj_bosstrans_knives_subway;
trans_order[8] = _order2;
trans_order[9] = _order3;
trans_order[10] = _order1;
trans_order[11] = _order0;
trans_order[12] = _order2;
trans_order[13] = _order3;
trans_order[14] = obj_bosstrans_knives_subway;
trans_order[15] = _order1;
trans_order[16] = _order2;
trans_order[17] = _order3;
trans_order[18] = _order0;
trans_order[19] = _order1;
trans_order[20] = _order2;
trans_order[21] = _order3;
trans_order[22] = _order0;
trans_order[23] = _order1;
event_user(0);
macro_room = rm_boomtown_boss_macro;
var _repeat1 = "baby_rattle";
games[0] = ["sketch_collect", "demoswing", "jetpack_smash", "karate_dodge", ["nude_match", 0]];
games[1] = ["mugshot", "apedino", "pistol", "coin", "monster_truck"];
games[2] = [_repeat1];
games[3] = ["gart_jump", "dodge", "ballbattle"];
games[4] = [["nude_match", 1], "monster_truck", "demoswing"];
games[4] = array_shuffle(games[4]);
array_delete(games[4], 0, 1);
games[5] = ["crate_memory", "jetpack_collect", "bec", "karate_dodge", "wizard_stab"];
speedups = [[7, 0.14285714285714285], [14, 0.07142857142857142]];
texture_prefetch("tg_bosstrans_knives");
sprite_prefetch(spr_bosstrans_knives_opening_buster);
sprite_prefetch(spr_bosstrans_knives_opening_knives);
my_audiogroup = bgm_endless_jingleA;
audio_group_load(bgm_endless_jingleA);
