{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms12_spr_phone_screen",
  "bbox_bottom": 47,
  "bbox_left": 0,
  "bbox_right": 115,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d4cad5d0-7e39-4e08-9c2d-50213a37d320",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5de74fb9-9aae-4452-881f-876c1f852d26",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"548923d4-7882-4ccd-8027-f2a6868fde1e",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 48,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"2d897909-2c1c-4b32-9f38-caf9db7ae800","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms12_spr_phone_screen",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d4cad5d0-7e39-4e08-9c2d-50213a37d320","path":"sprites/ms12_spr_phone_screen/ms12_spr_phone_screen.yy",},},},"Disabled":false,"id":"92278aa3-938c-4e74-9faf-a75c2add9e7e","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5de74fb9-9aae-4452-881f-876c1f852d26","path":"sprites/ms12_spr_phone_screen/ms12_spr_phone_screen.yy",},},},"Disabled":false,"id":"95534a64-68e2-45e1-ac07-bbb067c30a79","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"548923d4-7882-4ccd-8027-f2a6868fde1e","path":"sprites/ms12_spr_phone_screen/ms12_spr_phone_screen.yy",},},},"Disabled":false,"id":"8a1d3e49-d849-4d0a-9543-68bbb7f17955","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 125,
}