{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtSa3_spr_act3figmentsL",
  "bbox_bottom": 610,
  "bbox_left": 0,
  "bbox_right": 232,
  "bbox_top": 24,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f51552ed-2c31-44c8-b5bc-7e1391fa65c4",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"08ffc4af-064b-4f8b-93bb-ea46099541ab",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9a5fe90a-25b6-4250-a3df-501e28f7235c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"05be0a8a-b5f9-4193-810a-e9d4cf9d1d14",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 615,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"8bd14cac-40f1-4b83-932e-102dbe1d4b31","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 8,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtSa3_spr_act3figmentsL",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 5.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f51552ed-2c31-44c8-b5bc-7e1391fa65c4","path":"sprites/ibtSa3_spr_act3figmentsL/ibtSa3_spr_act3figmentsL.yy",},},},"Disabled":false,"id":"fee76a52-cf0a-4c02-94e7-e0e2a35d80cc","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"08ffc4af-064b-4f8b-93bb-ea46099541ab","path":"sprites/ibtSa3_spr_act3figmentsL/ibtSa3_spr_act3figmentsL.yy",},},},"Disabled":false,"id":"b7e88e1d-2244-4c8f-bafc-fe27b47f0857","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9a5fe90a-25b6-4250-a3df-501e28f7235c","path":"sprites/ibtSa3_spr_act3figmentsL/ibtSa3_spr_act3figmentsL.yy",},},},"Disabled":false,"id":"90f96235-b40d-4165-9b0d-a158c52f3831","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"05be0a8a-b5f9-4193-810a-e9d4cf9d1d14","path":"sprites/ibtSa3_spr_act3figmentsL/ibtSa3_spr_act3figmentsL.yy",},},},"Disabled":false,"id":"15f17d07-1d5d-4933-b255-2724c431c8b3","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 262,
    "yorigin": 615,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 262,
}