{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_pandorathoughts_unlit",
  "bbox_bottom": 349,
  "bbox_left": 214,
  "bbox_right": 479,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"52ddea82-b596-4981-be8f-17e4ffaf88d7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c2e913ee-629d-48a5-a2f7-102f6afb7ade",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"379d67df-10f6-45cd-98d0-d6f7ce4cd558",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"27c06801-8c03-41af-baea-7053a6e43e64",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 350,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"f14ef140-d2d2-42f6-8924-36117ee0c779","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 2,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_pandorathoughts_unlit",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 3.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"52ddea82-b596-4981-be8f-17e4ffaf88d7","path":"sprites/spr_pandorathoughts_unlit/spr_pandorathoughts_unlit.yy",},},},"Disabled":false,"id":"e6175e33-f988-41e7-8e7f-cff79a5c02c0","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c2e913ee-629d-48a5-a2f7-102f6afb7ade","path":"sprites/spr_pandorathoughts_unlit/spr_pandorathoughts_unlit.yy",},},},"Disabled":false,"id":"fe489a04-6eb9-4e50-84f0-a727be1c6347","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"379d67df-10f6-45cd-98d0-d6f7ce4cd558","path":"sprites/spr_pandorathoughts_unlit/spr_pandorathoughts_unlit.yy",},},},"Disabled":false,"id":"6a26beaf-a7b4-4254-911a-f1a1721f1fa6","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"27c06801-8c03-41af-baea-7053a6e43e64","path":"sprites/spr_pandorathoughts_unlit/spr_pandorathoughts_unlit.yy",},},},"Disabled":false,"id":"cccb886f-acdd-43ea-901a-f74335b77778","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 480,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}