{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms16_spr_ready",
  "bbox_bottom": 183,
  "bbox_left": 42,
  "bbox_right": 166,
  "bbox_top": 27,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8dc9f1cc-025c-464b-8ad7-6a420c523ae0",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"49778dc9-ae60-4c1a-950a-067a758a05e4",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a3aebd17-d09b-49d6-a202-faef09e61424",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 220,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"e27583f7-fff5-46b6-8b3d-2cd72a4bdaee","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms16_spr_ready",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8dc9f1cc-025c-464b-8ad7-6a420c523ae0","path":"sprites/ms16_spr_ready/ms16_spr_ready.yy",},},},"Disabled":false,"id":"439bd3e2-3c98-4b1a-b338-6ad450798d68","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"49778dc9-ae60-4c1a-950a-067a758a05e4","path":"sprites/ms16_spr_ready/ms16_spr_ready.yy",},},},"Disabled":false,"id":"35ad0ae1-5e7a-4e5b-a6c3-e9236d83c827","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a3aebd17-d09b-49d6-a202-faef09e61424","path":"sprites/ms16_spr_ready/ms16_spr_ready.yy",},},},"Disabled":false,"id":"834356f7-bdef-4a94-be4e-94e2952d7310","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 107,
    "yorigin": 183,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 215,
}