{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "sqcs_0_2_0_spr_smiles",
  "bbox_bottom": 293,
  "bbox_left": 24,
  "bbox_right": 502,
  "bbox_top": 75,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c32246a5-a7a1-4dc8-b7c4-6702d131e8a7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e5a05eb7-5039-446b-9c0b-3f08b60b8542",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"53932a96-5c0d-4cea-822f-c3a439a61d15",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 330,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"6ce61487-3549-438f-94f4-d4d5baf2388b","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "sqcs_0_2_0_spr_smiles",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 11.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c32246a5-a7a1-4dc8-b7c4-6702d131e8a7","path":"sprites/sqcs_0_2_0_spr_smiles/sqcs_0_2_0_spr_smiles.yy",},},},"Disabled":false,"id":"bc92d04c-9db4-433e-b7f2-9fa731356adf","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e5a05eb7-5039-446b-9c0b-3f08b60b8542","path":"sprites/sqcs_0_2_0_spr_smiles/sqcs_0_2_0_spr_smiles.yy",},},},"Disabled":false,"id":"9d8bcc41-56e0-43c1-a8cd-94e80e45fd29","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"53932a96-5c0d-4cea-822f-c3a439a61d15","path":"sprites/sqcs_0_2_0_spr_smiles/sqcs_0_2_0_spr_smiles.yy",},},},"Disabled":false,"id":"2b91a68f-6407-40ec-8ebd-d2d95626a6bc","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 275,
    "yorigin": 165,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 550,
}