{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_leaderboard_tabbtn_friends",
  "bbox_bottom": 11,
  "bbox_left": 0,
  "bbox_right": 41,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d9c456b4-b69d-40b7-8b94-bb925c7d50bb",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"492e76ee-cf46-41dd-b853-f43271c68993",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 12,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"0936fd49-b041-46d6-a92a-3b481a40542c","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": {
    "resourceType": "GMNineSliceData",
    "resourceVersion": "1.0",
    "bottom": 1,
    "enabled": true,
    "guideColour": [
      4294902015,
      4294902015,
      4294902015,
      4294902015,
      4294902015,
    ],
    "highlightColour": 1728023040,
    "highlightStyle": 0,
    "left": 6,
    "right": 6,
    "tileMode": [
      0,
      0,
      0,
      0,
      0,
    ],
    "top": 1,
  },
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_leaderboard_tabbtn_friends",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 2.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d9c456b4-b69d-40b7-8b94-bb925c7d50bb","path":"sprites/spr_leaderboard_tabbtn_friends/spr_leaderboard_tabbtn_friends.yy",},},},"Disabled":false,"id":"2ff8e34d-0f89-4291-9b11-6a5325b68725","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"492e76ee-cf46-41dd-b853-f43271c68993","path":"sprites/spr_leaderboard_tabbtn_friends/spr_leaderboard_tabbtn_friends.yy",},},},"Disabled":false,"id":"238c72c3-1c89-43bd-bfa5-3b7b33f88b83","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 42,
}