{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_mmui_hoverimg1_fill",
  "bbox_bottom": 250,
  "bbox_left": 308,
  "bbox_right": 448,
  "bbox_top": 17,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8560b8fe-c8e6-43e0-a468-96f68c15b833",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"aeab047f-cf9c-470f-bf3e-2880712e68a6",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"7b8cf985-59a7-4da9-bbd5-c11ab11bf34a",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"0fa2a0bd-70e1-4bac-9388-657d0d3d2339","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_mmui_hoverimg1_fill",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8560b8fe-c8e6-43e0-a468-96f68c15b833","path":"sprites/spr_mmui_hoverimg1_fill/spr_mmui_hoverimg1_fill.yy",},},},"Disabled":false,"id":"c52de137-a416-4761-beb4-285b63e04d18","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"aeab047f-cf9c-470f-bf3e-2880712e68a6","path":"sprites/spr_mmui_hoverimg1_fill/spr_mmui_hoverimg1_fill.yy",},},},"Disabled":false,"id":"9f5964bb-89b8-406a-a74f-16498283d368","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"7b8cf985-59a7-4da9-bbd5-c11ab11bf34a","path":"sprites/spr_mmui_hoverimg1_fill/spr_mmui_hoverimg1_fill.yy",},},},"Disabled":false,"id":"36fdeffa-427d-4986-b82e-cd8a2e4638e2","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}