{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "msboss_spr_portal_mask",
  "bbox_bottom": 67,
  "bbox_left": -91,
  "bbox_right": 265,
  "bbox_top": 0,
  "bboxMode": 2,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2bb6f6d8-bb7d-4a8a-85ee-f156122efb67",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"cc20e190-5932-4a6f-bb9e-2dda0bc54414",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"0612afac-fe88-473e-b0fb-e2d573d40d9b",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 70,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"5247ffe2-4191-4102-8bff-3a3cb9183ff3","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "msboss_spr_portal_mask",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 3.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2bb6f6d8-bb7d-4a8a-85ee-f156122efb67","path":"sprites/msboss_spr_portal_mask/msboss_spr_portal_mask.yy",},},},"Disabled":false,"id":"e74444a8-5f73-4017-8dbb-a30a6139fd0e","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"cc20e190-5932-4a6f-bb9e-2dda0bc54414","path":"sprites/msboss_spr_portal_mask/msboss_spr_portal_mask.yy",},},},"Disabled":false,"id":"1b77c977-84b2-4816-9ea4-9d4c6b3b92f8","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"0612afac-fe88-473e-b0fb-e2d573d40d9b","path":"sprites/msboss_spr_portal_mask/msboss_spr_portal_mask.yy",},},},"Disabled":false,"id":"84eb0417-c149-45f7-9ad4-bd0e8f3e121c","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 84,
    "yorigin": 35,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 169,
}