{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_dialogue_log_frame_topelec2",
  "bbox_bottom": 25,
  "bbox_left": 219,
  "bbox_right": 241,
  "bbox_top": 17,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9343a018-b9ed-453d-9220-3ae0e8ba124a",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e42f6225-236f-4240-a869-ed24b2084673",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8c332808-e1c5-4ae8-8366-d41c1c76e27c",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"4a205cd9-ec00-4e53-a5e8-58828662cb0b","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_dialogue_log_frame_topelec2",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 3.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9343a018-b9ed-453d-9220-3ae0e8ba124a","path":"sprites/spr_dialogue_log_frame_topelec2/spr_dialogue_log_frame_topelec2.yy",},},},"Disabled":false,"id":"5ce96e93-fc9e-48db-8be6-d3ab66fccf02","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e42f6225-236f-4240-a869-ed24b2084673","path":"sprites/spr_dialogue_log_frame_topelec2/spr_dialogue_log_frame_topelec2.yy",},},},"Disabled":false,"id":"a0f26fed-d98f-4da4-9f77-7c01d224c464","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8c332808-e1c5-4ae8-8366-d41c1c76e27c","path":"sprites/spr_dialogue_log_frame_topelec2/spr_dialogue_log_frame_topelec2.yy",},},},"Disabled":false,"id":"a27b20d9-dba5-40b0-9aab-1a0ecbc9f8f1","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}