{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf1_spr_player_downleft",
  "bbox_bottom": 63,
  "bbox_left": 0,
  "bbox_right": 38,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"dd01fbf0-d70c-40c7-b9e0-e26a941694b7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"ffa74cbf-8282-44af-8dd9-652715c8598d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2317d18f-1374-49d7-84f6-cb5defff8d86",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b33ec831-cd58-4760-acdd-defdd07b0976",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 64,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"648fd557-05c5-4d5f-89ad-a611b770311d","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf1_spr_player_downleft",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"dd01fbf0-d70c-40c7-b9e0-e26a941694b7","path":"sprites/mf1_spr_player_downleft/mf1_spr_player_downleft.yy",},},},"Disabled":false,"id":"e33ef391-816d-4738-b4a2-736d8430976e","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"ffa74cbf-8282-44af-8dd9-652715c8598d","path":"sprites/mf1_spr_player_downleft/mf1_spr_player_downleft.yy",},},},"Disabled":false,"id":"8d39ba39-b486-4812-bef6-2dd5142d7cbe","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2317d18f-1374-49d7-84f6-cb5defff8d86","path":"sprites/mf1_spr_player_downleft/mf1_spr_player_downleft.yy",},},},"Disabled":false,"id":"e829aa70-9923-477c-ad7a-1a71d945ee44","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b33ec831-cd58-4760-acdd-defdd07b0976","path":"sprites/mf1_spr_player_downleft/mf1_spr_player_downleft.yy",},},},"Disabled":false,"id":"c27c34bf-fb1c-4be1-b2cc-cb178f4ce56e","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 14,
    "yorigin": 58,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 39,
}