{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms1_spr_askwater",
  "bbox_bottom": 26,
  "bbox_left": 0,
  "bbox_right": 30,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8dbafcc6-3905-41aa-93cb-74126d19278b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"45c57a45-4049-49f2-8281-2fc6b552e416",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c1f1a690-8181-480b-99db-490a9d6ace8e",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 27,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"4e0534e2-f43b-4d23-9afd-cb6d88045317","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 6,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms1_spr_askwater",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 4.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8dbafcc6-3905-41aa-93cb-74126d19278b","path":"sprites/ms1_spr_askwater/ms1_spr_askwater.yy",},},},"Disabled":false,"id":"7f14504f-73cb-4c0c-b1bb-e30a05c70f6c","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"45c57a45-4049-49f2-8281-2fc6b552e416","path":"sprites/ms1_spr_askwater/ms1_spr_askwater.yy",},},},"Disabled":false,"id":"311846c0-fa81-4d45-bb7c-7fcc51ca95d0","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c1f1a690-8181-480b-99db-490a9d6ace8e","path":"sprites/ms1_spr_askwater/ms1_spr_askwater.yy",},},},"Disabled":false,"id":"ca7797c8-cb23-4920-96d1-4e800dcbe762","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 27,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 31,
}