{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms9_spr_loseframe",
  "bbox_bottom": 173,
  "bbox_left": 1,
  "bbox_right": 173,
  "bbox_top": 1,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": true,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"80fee840-7198-429f-bd2c-088e9ceb4f70",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6c9591ad-975b-43ce-98a1-a39dee125f4a",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 175,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"00a55b7e-a0f5-4e2b-8107-23bab38bdc3d","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms9_spr_loseframe",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 2.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 5.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"80fee840-7198-429f-bd2c-088e9ceb4f70","path":"sprites/ms9_spr_loseframe/ms9_spr_loseframe.yy",},},},"Disabled":false,"id":"2318bee1-2f5a-4a60-b771-bae6018191e8","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6c9591ad-975b-43ce-98a1-a39dee125f4a","path":"sprites/ms9_spr_loseframe/ms9_spr_loseframe.yy",},},},"Disabled":false,"id":"75db1c1b-e584-42eb-9985-d37bce406dc3","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 87,
    "yorigin": 87,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 175,
}