{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms0_spr_flag",
  "bbox_bottom": 28,
  "bbox_left": -11,
  "bbox_right": 32,
  "bbox_top": 0,
  "bboxMode": 2,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2ef84cd8-5aeb-422c-8a65-20de37612427",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c4e95858-6c64-4984-b5eb-cc15202f1fb2",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2c8b0047-3bfc-40fd-b1fe-92f32f45afe3",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 29,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"e78ea055-9ffc-4a59-9339-c45e57a83346","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms0_spr_flag",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 4.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2ef84cd8-5aeb-422c-8a65-20de37612427","path":"sprites/ms0_spr_flag/ms0_spr_flag.yy",},},},"Disabled":false,"id":"2e57a4ce-cd35-403b-b891-11cb76a03598","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c4e95858-6c64-4984-b5eb-cc15202f1fb2","path":"sprites/ms0_spr_flag/ms0_spr_flag.yy",},},},"Disabled":false,"id":"e0ee0b3c-583c-427c-bb41-7ccfdd6c4ab0","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2c8b0047-3bfc-40fd-b1fe-92f32f45afe3","path":"sprites/ms0_spr_flag/ms0_spr_flag.yy",},},},"Disabled":false,"id":"0c243a29-6616-4f4c-806b-37295cd63851","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 18,
    "yorigin": 29,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 21,
}