scribble_anim_wave(0.5, 3, 0.5);
global.coopGame = false;
randomize();
global.RandomSeed = random_get_seed();
pal_swap_init_system(shd_pal_swapper, shd_pal_html_sprite, shd_pal_html_surface);
global.SouractiveProgression = 0;
global.levelname = "none";
global.firstlvlRoom = hub_w1;
global.secretfound = 0;
global.showplaytimer = false;
global.playmiliseconds = 0;
global.playseconds = 0;
global.playminutes = 0;
global.playhour = 0;
global.fill = 0;
global.savedfill = 0;
global.ExitGateTaunt = 0;
global.freezeframe = false;
global.greyscalefade = 0;
global.music = -4;
global.harrymusic = -4;
global.shopmusic = -4;
global.PAUSE_contTrack_pos = 0;
global.DialogMessage = 0;
global.dialogchoices = 0;
global.choiced = 0;
global.dancetimer = 0;
global.maxdancetimer = 0;
global.martian_alarmed = false;
global.minesProgress = false;
global.MinesFlags[UnknownEnum.Value_0] = false;
global.MinesFlags[UnknownEnum.Value_1] = false;
global.MinesFlags[UnknownEnum.Value_2] = false;
global.MinesFlags[UnknownEnum.Value_3] = false;
global.MinesFlags[UnknownEnum.Value_4] = false;
global.MinesFlags[UnknownEnum.Value_5] = false;
global.MinesFlags[UnknownEnum.Value_6] = false;
global.cutsceneManager = -4;
global.combomode = false;
global.font = __scribble_font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.0123456789:- ", 1, 0);
global.smallfont = __scribble_font_add_sprite_ext(spr_smallfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-:", 1, 0);
global.creditsfont = __scribble_font_add_sprite_ext(spr_creditsfont, " ABCDEFGHIJKLMNOPQRSTUVWXYZ.!,abcdefghijklmnopqrstuvwxyz0123456789@#$%^&*(){}[]|:;'/`", 1, 0);
global.combofont = __scribble_font_add_sprite_ext(spr_fontcombo, "0123456789", 1, 0);
global.collectfont = __scribble_font_add_sprite_ext(spr_fontcollect, "0123456789", 1, 0);
global.candlefont = __scribble_font_add_sprite_ext(spr_fontcandle, "0123456789", 1, 0);
global.rankcombofont = __scribble_font_add_sprite_ext(spr_fontrankcombo, "0123456789", 1, 0);
global.bubblefont = __scribble_font_add_sprite_ext(spr_bubblefont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", 1, 0);
global.timerfont = __scribble_font_add_sprite_ext(spr_timer_font, "1234567890", 0, 6);
global.combofont = __scribble_font_add_sprite_ext(spr_combometer_font, "1234567890x", 1, 2);
global.lapfont = __scribble_font_add_sprite_ext(spr_lap_font, "0123456789", 1, 2);
global.dialogfont = __scribble_font_add_sprite_ext(spr_font_dialogue, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz,.!?:;`'/-_+=1234567890@#$%^&*()[]", 1, 2);
global.buttonfont = __scribble_font_add_sprite_ext(spr_buttonfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZ$%&*()/", 1, 0);
global.promptfont = __scribble_font_add_sprite_ext(spr_promptfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.:!0123456789?'\"ÁÉÍÓÚáéíóú_-[]▼()&#风雨廊桥전태양*яиБжидГзвбнль", 1, 0);
global.npcfont = __scribble_font_add_sprite_ext(spr_npcfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!,.:0123456789'?-", 1, 2);
global.cafefont = __scribble_font_add_sprite_ext(spr_cafefontbig, "0123456789:", 1, 0);
global.cafefontsmall = __scribble_font_add_sprite_ext(spr_cafefontsmall, "0123456789:", 1, 0);
global.shellactivate = false;
global.showcollisions = false;
global.showtiles = true;
global.DebugMode = false;
global.fartcounter = 0;
global.showcollisions = true;
global.parallaxbg_surface = -4;
global.ParallaxMap = ds_map_create();
scr_default_parallax(true);
global.FollowerList = ds_list_create();
global.KeyFollowerList = ds_list_create();
global.MallowFollow = false;
global.CrackFollow = false;
global.ChocoFollow = false;
global.WormFollow = false;
global.CandyFollow = false;
global.janitorRudefollow = false;
global.janitorLapfollow = false;
global.Donutfollow = false;
global.janitortype = 1;
global.lapcount = 0;
global.CafeDrawer = -4;
global.player_input_device = -2;
global.player_input_device2 = -2;
global.targetCamX = 0;
global.targetCamY = 0;
global.resolutions = [[480, 270], [960, 540], [1024, 576], [1280, 720], [1600, 900], [1920, 1080]];
init_option();
set_resolution_option(global.selectedResolution);
window_set_fullscreen(global.fullscreen);
gml_release_mode(true);
scr_initKeyNameMap();
global.doorsave = ds_list_create();
global.afterimage_list = ds_list_create();
