global.game_music = "bgm_micro_superhero";
hspd = 0;
vspd = 0;
flyspd = 8.5;
sprite = [spr_Bu_superhero_planet0, spr_Bu_superhero_planet1, spr_Bu_superhero_planet2];
sprite = array_shuffle(sprite);
sprite[3] = choose(sprite[0], sprite[1]);
alarm[0] = 1;
wind_snd = -4;
anim_init();
wind_snd = -4;
