{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "sqcs_0_2_0_spr_sparks",
  "bbox_bottom": 290,
  "bbox_left": 36,
  "bbox_right": 511,
  "bbox_top": 31,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f03b7e5c-cf76-4d89-8edf-a0c40b78841b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"70b3941f-3b2e-4cde-97cc-b3a0e52e8900",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6880fe52-dfc6-4590-b961-74c1a5b71e36",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 330,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"93ff08e2-981d-4f4c-aff7-5c08adff8868","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "sqcs_0_2_0_spr_sparks",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 33.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f03b7e5c-cf76-4d89-8edf-a0c40b78841b","path":"sprites/sqcs_0_2_0_spr_sparks/sqcs_0_2_0_spr_sparks.yy",},},},"Disabled":false,"id":"194bfc34-9c02-4aa5-afd3-43b6cf46d3f5","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"70b3941f-3b2e-4cde-97cc-b3a0e52e8900","path":"sprites/sqcs_0_2_0_spr_sparks/sqcs_0_2_0_spr_sparks.yy",},},},"Disabled":false,"id":"1a67b752-180e-41e3-8b63-c4258569338f","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6880fe52-dfc6-4590-b961-74c1a5b71e36","path":"sprites/sqcs_0_2_0_spr_sparks/sqcs_0_2_0_spr_sparks.yy",},},},"Disabled":false,"id":"abf0eb1f-f49f-4898-a9a4-fbf14500dd9a","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 275,
    "yorigin": 165,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 550,
}