testvariablenothing = false;
draw_set_font(global.font_splash);
draw_set_valign(fa_bottom);
draw_text_transformed((1900 + (400 * save_out)) - 500, 1065, save_text, 0.5, 0.5, 0);
draw_set_color(c_lime);
draw_set_alpha(save_text_flash);
draw_text_transformed((1900 + (400 * save_out)) - 500, 1065, save_text, 0.5, 0.5, 0);
draw_set_alpha(1);
draw_set_color(c_white);
draw_set_valign(fa_top);
