{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_mmui_hoverimg2_fill",
  "bbox_bottom": 213,
  "bbox_left": 269,
  "bbox_right": 467,
  "bbox_top": 54,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a0f1bc95-43c3-442c-9038-7387bf0e4f72",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f35aafe3-309b-45f5-b96a-7fb4f651ae26",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"785c5b0e-3d98-4e01-bf50-734cba805954",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"7e4fff87-bc61-487c-bc45-113e89083aac","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_mmui_hoverimg2_fill",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a0f1bc95-43c3-442c-9038-7387bf0e4f72","path":"sprites/spr_mmui_hoverimg2_fill/spr_mmui_hoverimg2_fill.yy",},},},"Disabled":false,"id":"ec0c1de7-3543-4bf7-a9a0-7bc4344a6496","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f35aafe3-309b-45f5-b96a-7fb4f651ae26","path":"sprites/spr_mmui_hoverimg2_fill/spr_mmui_hoverimg2_fill.yy",},},},"Disabled":false,"id":"dd44dfe8-e271-4604-b47d-8e40e6907460","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"785c5b0e-3d98-4e01-bf50-734cba805954","path":"sprites/spr_mmui_hoverimg2_fill/spr_mmui_hoverimg2_fill.yy",},},},"Disabled":false,"id":"bea7fda6-60a7-40e8-91fb-6fc683e1062d","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}