{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_sparkle_elevator_bg",
  "bbox_bottom": 329,
  "bbox_left": 0,
  "bbox_right": 549,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"62868165-e488-46dd-8432-26bd6e5f2b9b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9dbfd2ef-e5ef-4f30-83fd-f22437009010",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"fc09f276-4c39-4346-97f2-a75e035caeb8",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 330,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"4193b9ba-95cb-43dc-bbf3-0bd81315240c","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_sparkle_elevator_bg",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"62868165-e488-46dd-8432-26bd6e5f2b9b","path":"sprites/spr_sparkle_elevator_bg/spr_sparkle_elevator_bg.yy",},},},"Disabled":false,"id":"bd2df59c-0769-4d6e-9379-d5d6c1d208ed","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9dbfd2ef-e5ef-4f30-83fd-f22437009010","path":"sprites/spr_sparkle_elevator_bg/spr_sparkle_elevator_bg.yy",},},},"Disabled":false,"id":"6053d27f-cf71-4d39-9263-9c40e73daeb8","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"fc09f276-4c39-4346-97f2-a75e035caeb8","path":"sprites/spr_sparkle_elevator_bg/spr_sparkle_elevator_bg.yy",},},},"Disabled":false,"id":"46fdca43-c89f-46ca-9517-d955556b18b5","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 275,
    "yorigin": 165,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 550,
}