{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf1_spr_player_right",
  "bbox_bottom": 62,
  "bbox_left": 0,
  "bbox_right": 28,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d7bb9f8e-aa46-483f-8082-90dd002f1fd1",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"ec4f8535-6edb-4233-9059-489c16aea285",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"73b78d04-9ee6-472e-9fcc-20d60d75de66",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"7ab14f9e-5c2f-49f4-a491-2a97ebc1368b",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 63,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"575e9e3d-d12b-4969-a3d7-8b9918fc780d","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf1_spr_player_right",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d7bb9f8e-aa46-483f-8082-90dd002f1fd1","path":"sprites/mf1_spr_player_right/mf1_spr_player_right.yy",},},},"Disabled":false,"id":"4201104e-376a-4f18-ab67-c01fb9707a84","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"ec4f8535-6edb-4233-9059-489c16aea285","path":"sprites/mf1_spr_player_right/mf1_spr_player_right.yy",},},},"Disabled":false,"id":"8e4ec05e-7eab-4b9e-82cd-620a08b923aa","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"73b78d04-9ee6-472e-9fcc-20d60d75de66","path":"sprites/mf1_spr_player_right/mf1_spr_player_right.yy",},},},"Disabled":false,"id":"12f78eae-4977-4df0-bdd6-6cb404b5bbf7","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"7ab14f9e-5c2f-49f4-a491-2a97ebc1368b","path":"sprites/mf1_spr_player_right/mf1_spr_player_right.yy",},},},"Disabled":false,"id":"967140d0-3e58-4944-8a82-ed8d37448e59","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 20,
    "yorigin": 62,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 29,
}