{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtS_spr_lifelose",
  "bbox_bottom": 54,
  "bbox_left": 0,
  "bbox_right": 65,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"fc594e63-2e03-40b7-afc6-5533c7d7c9c9",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"37dddb88-0d72-4411-a470-c92f0e74da9d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9c0854ad-01c8-40a3-965e-64db4c145008",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e436dba7-dfa0-40a5-9098-327bb8ba20c2",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 55,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"50f12457-0c68-4be0-ba6b-3ba070e50cde","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtS_spr_lifelose",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 7.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"fc594e63-2e03-40b7-afc6-5533c7d7c9c9","path":"sprites/ibtS_spr_lifelose/ibtS_spr_lifelose.yy",},},},"Disabled":false,"id":"dca0dd62-da52-4efb-9b22-bb756c807fcc","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"37dddb88-0d72-4411-a470-c92f0e74da9d","path":"sprites/ibtS_spr_lifelose/ibtS_spr_lifelose.yy",},},},"Disabled":false,"id":"e7d7a4d2-c5a8-40bb-812c-418ca46d416c","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9c0854ad-01c8-40a3-965e-64db4c145008","path":"sprites/ibtS_spr_lifelose/ibtS_spr_lifelose.yy",},},},"Disabled":false,"id":"4899e904-8ed1-4a5d-b32d-5e83e23e2161","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e436dba7-dfa0-40a5-9098-327bb8ba20c2","path":"sprites/ibtS_spr_lifelose/ibtS_spr_lifelose.yy",},},},"Disabled":false,"id":"64fcdf48-819c-4841-8df4-80ad62fb7ffc","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 33,
    "yorigin": 27,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 66,
}