{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf2_spr_brain",
  "bbox_bottom": 33,
  "bbox_left": 4,
  "bbox_right": 31,
  "bbox_top": 6,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"4134c9d3-672f-487e-bf80-dc16f01f2122",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d5fa9d19-47ba-4991-856d-23b616036c3d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8d21ab6e-f8db-4640-a9dc-69793a0282e8",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2abca2ce-b06e-49cb-848b-069595045145",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 35,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"82e5fb63-f557-4b20-bceb-783a85e391c9","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf2_spr_brain",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 33.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"4134c9d3-672f-487e-bf80-dc16f01f2122","path":"sprites/mf2_spr_brain/mf2_spr_brain.yy",},},},"Disabled":false,"id":"7fc32ba8-cc61-4b5d-a071-8d1c595d27d6","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d5fa9d19-47ba-4991-856d-23b616036c3d","path":"sprites/mf2_spr_brain/mf2_spr_brain.yy",},},},"Disabled":false,"id":"e6155ef6-eff7-42e8-a19c-4fd4cced63f8","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8d21ab6e-f8db-4640-a9dc-69793a0282e8","path":"sprites/mf2_spr_brain/mf2_spr_brain.yy",},},},"Disabled":false,"id":"ff24deca-0541-45e7-bf28-22516f27e90a","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2abca2ce-b06e-49cb-848b-069595045145","path":"sprites/mf2_spr_brain/mf2_spr_brain.yy",},},},"Disabled":false,"id":"c3ecc40c-ad81-47a5-8e30-1cd33d209745","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 17,
    "yorigin": 17,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 35,
}