{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf1_spr_player_down",
  "bbox_bottom": 62,
  "bbox_left": 0,
  "bbox_right": 51,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"65e543a4-d692-4f99-b05a-eba41273dd27",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"3b7cbe0f-9c91-4c99-9279-094168926430",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a34e303e-4b7f-4abb-8be7-a875510b3eed",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"ca24793b-d55d-4df7-9687-d0c5f04c60f2",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 63,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"7ec07887-8260-49a8-a1f9-1579642d347e","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 7,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf1_spr_player_down",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"65e543a4-d692-4f99-b05a-eba41273dd27","path":"sprites/mf1_spr_player_down/mf1_spr_player_down.yy",},},},"Disabled":false,"id":"d6f6d848-43a6-4f78-8454-c9fac6a48761","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"3b7cbe0f-9c91-4c99-9279-094168926430","path":"sprites/mf1_spr_player_down/mf1_spr_player_down.yy",},},},"Disabled":false,"id":"c9988e58-5c0f-4d7a-9dfc-a43045cc2c6a","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a34e303e-4b7f-4abb-8be7-a875510b3eed","path":"sprites/mf1_spr_player_down/mf1_spr_player_down.yy",},},},"Disabled":false,"id":"828c2712-c65b-425a-8425-85126b773840","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"ca24793b-d55d-4df7-9687-d0c5f04c60f2","path":"sprites/mf1_spr_player_down/mf1_spr_player_down.yy",},},},"Disabled":false,"id":"1b8c6647-af54-4dba-8c69-c5d6ae50916b","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 26,
    "yorigin": 63,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 52,
}