{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mt4_spr_shadow",
  "bbox_bottom": 33,
  "bbox_left": 0,
  "bbox_right": 89,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 0,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d4274403-e368-4e48-b333-7ed17633899e",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"4c048695-56ea-4bbb-a111-88f36a0ffe01",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"bf0a16f3-26aa-4795-9950-8589d8590b74",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 34,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"579def21-4e69-415d-8caa-e2f14044edc4","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mt4_spr_shadow",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 20.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d4274403-e368-4e48-b333-7ed17633899e","path":"sprites/mt4_spr_shadow/mt4_spr_shadow.yy",},},},"Disabled":false,"id":"50367c35-89da-4fb4-a4cd-9517ec6a4041","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"4c048695-56ea-4bbb-a111-88f36a0ffe01","path":"sprites/mt4_spr_shadow/mt4_spr_shadow.yy",},},},"Disabled":false,"id":"09d53ccd-29d2-47fb-9517-b1ee6356b628","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"bf0a16f3-26aa-4795-9950-8589d8590b74","path":"sprites/mt4_spr_shadow/mt4_spr_shadow.yy",},},},"Disabled":false,"id":"7482abe4-573a-4366-a597-eadc807af40d","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 45,
    "yorigin": 17,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 90,
}