{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms12_spr_cursor",
  "bbox_bottom": 22,
  "bbox_left": 0,
  "bbox_right": 16,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5b69e494-906c-4db9-a570-78a2d2375fbb",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2c38fd27-18b3-4518-98cd-59d7cb75a099",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"fc123482-358b-4cb3-b9fd-105fd7ac76c7",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 23,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"49cd1e6f-5158-4a27-85e8-4e250a7310c6","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms12_spr_cursor",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 0.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5b69e494-906c-4db9-a570-78a2d2375fbb","path":"sprites/ms12_spr_cursor/ms12_spr_cursor.yy",},},},"Disabled":false,"id":"eb5a625f-eded-471e-82bb-40b55554fb56","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2c38fd27-18b3-4518-98cd-59d7cb75a099","path":"sprites/ms12_spr_cursor/ms12_spr_cursor.yy",},},},"Disabled":false,"id":"4e4dc3ad-ce0c-4313-b924-0374ef3fb70f","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"fc123482-358b-4cb3-b9fd-105fd7ac76c7","path":"sprites/ms12_spr_cursor/ms12_spr_cursor.yy",},},},"Disabled":false,"id":"f7163262-141f-4861-91b6-57888b2eeb65","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 5,
    "yorigin": 1,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 17,
}