{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtSl1_spr_lose1_mask",
  "bbox_bottom": 269,
  "bbox_left": 153,
  "bbox_right": 327,
  "bbox_top": 1,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"78269eea-0b34-49a0-954c-34aad9370631",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d65b75fd-866e-47a0-8c1d-eeea32acce5d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"75917a45-bd0b-4d1b-9270-20f80d682dce",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"fdc0bf2f-2ca7-4843-996d-51c350df10f8",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"0515674d-6f45-440e-b135-405cc88a738f","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtSl1_spr_lose1_mask",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"78269eea-0b34-49a0-954c-34aad9370631","path":"sprites/ibtSl1_spr_lose1_mask/ibtSl1_spr_lose1_mask.yy",},},},"Disabled":false,"id":"a36ee2a6-f8c4-4c5e-aa9f-caa73dd8389f","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d65b75fd-866e-47a0-8c1d-eeea32acce5d","path":"sprites/ibtSl1_spr_lose1_mask/ibtSl1_spr_lose1_mask.yy",},},},"Disabled":false,"id":"12f9ee7e-d9bb-4ff2-a0f9-3c86ecf2d815","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"75917a45-bd0b-4d1b-9270-20f80d682dce","path":"sprites/ibtSl1_spr_lose1_mask/ibtSl1_spr_lose1_mask.yy",},},},"Disabled":false,"id":"74e61fad-e73d-40a1-b0dd-e9106212391d","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"fdc0bf2f-2ca7-4843-996d-51c350df10f8","path":"sprites/ibtSl1_spr_lose1_mask/ibtSl1_spr_lose1_mask.yy",},},},"Disabled":false,"id":"1c8e14f8-3b6f-49ca-a877-0e0c017b3cc9","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}