{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "cs_0_0_3_spr_pandora",
  "bbox_bottom": 487,
  "bbox_left": 0,
  "bbox_right": 288,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a66688f9-b970-4bee-913e-7f7523a49ea6",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5773fdc5-043b-4d54-923b-4b29be3d143c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e8f94979-3864-4e32-8e74-58a39a64d80c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"52f8aa39-590f-4fb6-9363-175e27cb6b7a",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 488,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"7cecde04-67fc-4526-bd9a-e908d717fdff","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "cs_0_0_3_spr_pandora",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 2.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a66688f9-b970-4bee-913e-7f7523a49ea6","path":"sprites/cs_0_0_3_spr_pandora/cs_0_0_3_spr_pandora.yy",},},},"Disabled":false,"id":"453a7c9a-cc8a-4c50-a676-3d84281bf52f","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5773fdc5-043b-4d54-923b-4b29be3d143c","path":"sprites/cs_0_0_3_spr_pandora/cs_0_0_3_spr_pandora.yy",},},},"Disabled":false,"id":"d1460187-4498-4855-ab95-169e274506d5","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e8f94979-3864-4e32-8e74-58a39a64d80c","path":"sprites/cs_0_0_3_spr_pandora/cs_0_0_3_spr_pandora.yy",},},},"Disabled":false,"id":"04b0b853-837c-4fbf-88b1-f94dfa5a4027","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"52f8aa39-590f-4fb6-9363-175e27cb6b7a","path":"sprites/cs_0_0_3_spr_pandora/cs_0_0_3_spr_pandora.yy",},},},"Disabled":false,"id":"9ca8e8f0-f1b1-4c6c-965e-15fffd12dcf8","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 138,
    "yorigin": 270,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 289,
}