{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms12_spr_won_phone",
  "bbox_bottom": 130,
  "bbox_left": 0,
  "bbox_right": 83,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"02473911-3ee4-4a25-88fb-7c35962afa3d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"4986a8b9-4fe6-4970-8913-b6c2bfbf177b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"594c6c7d-4f44-444b-b816-19b6aa17809e",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"063d9806-26af-40ae-a40c-d2771806fdd7",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 131,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"99bf2599-372a-4d31-83de-f72061c0f6b3","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms12_spr_won_phone",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"02473911-3ee4-4a25-88fb-7c35962afa3d","path":"sprites/ms12_spr_won_phone/ms12_spr_won_phone.yy",},},},"Disabled":false,"id":"f768aa49-e0d6-48a4-af25-3940977ec99f","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"4986a8b9-4fe6-4970-8913-b6c2bfbf177b","path":"sprites/ms12_spr_won_phone/ms12_spr_won_phone.yy",},},},"Disabled":false,"id":"9116efdc-6af9-446c-aeab-f1c997a602b3","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"594c6c7d-4f44-444b-b816-19b6aa17809e","path":"sprites/ms12_spr_won_phone/ms12_spr_won_phone.yy",},},},"Disabled":false,"id":"c2c76af4-c604-439d-a45a-b9e3a9aa024e","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"063d9806-26af-40ae-a40c-d2771806fdd7","path":"sprites/ms12_spr_won_phone/ms12_spr_won_phone.yy",},},},"Disabled":false,"id":"c5256167-b9a7-4326-a1d0-23fc049265a7","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 42,
    "yorigin": 65,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 84,
}