{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms16_spr_left",
  "bbox_bottom": 186,
  "bbox_left": 25,
  "bbox_right": 159,
  "bbox_top": 36,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"cada9b2f-c5d1-402f-ac59-fa0ffadfe1f6",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f8fa4340-d5de-4bb7-9a2c-8e84f5b57a64",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"300ab692-28d5-4536-ab7c-6a43a91d9bc1",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 220,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"165a37f2-3e36-4f8a-98df-27bd972d7f89","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms16_spr_left",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"cada9b2f-c5d1-402f-ac59-fa0ffadfe1f6","path":"sprites/ms16_spr_left/ms16_spr_left.yy",},},},"Disabled":false,"id":"40b1db07-d3e8-47d8-9307-ff77b403d38f","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f8fa4340-d5de-4bb7-9a2c-8e84f5b57a64","path":"sprites/ms16_spr_left/ms16_spr_left.yy",},},},"Disabled":false,"id":"8916b269-e1a2-4e55-983d-c31843e304ed","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"300ab692-28d5-4536-ab7c-6a43a91d9bc1","path":"sprites/ms16_spr_left/ms16_spr_left.yy",},},},"Disabled":false,"id":"e5f3aadc-c014-4e6b-813c-07244556aacc","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 107,
    "yorigin": 183,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 215,
}