{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtSa3_spr_act3figmentsR",
  "bbox_bottom": 606,
  "bbox_left": 42,
  "bbox_right": 253,
  "bbox_top": 2,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6d489582-b80b-463a-aabb-6ed008d29219",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2b988dba-8e79-47f1-aeeb-9ef8d698d246",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"84fcd5a1-915b-471d-96e2-e3c9a3dd5bf2",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e8dc7a9d-c6a8-4295-86d5-0f675abd17c3",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 615,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"8552288a-0468-489d-aae1-13b5bd8b89de","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 6,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtSa3_spr_act3figmentsR",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 5.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6d489582-b80b-463a-aabb-6ed008d29219","path":"sprites/ibtSa3_spr_act3figmentsR/ibtSa3_spr_act3figmentsR.yy",},},},"Disabled":false,"id":"e28b3a52-e70c-4b86-b3ba-6612087f30c0","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2b988dba-8e79-47f1-aeeb-9ef8d698d246","path":"sprites/ibtSa3_spr_act3figmentsR/ibtSa3_spr_act3figmentsR.yy",},},},"Disabled":false,"id":"2945f7cb-e35d-4cae-ae46-58bba4474cc6","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"84fcd5a1-915b-471d-96e2-e3c9a3dd5bf2","path":"sprites/ibtSa3_spr_act3figmentsR/ibtSa3_spr_act3figmentsR.yy",},},},"Disabled":false,"id":"a4da7bb6-f553-413d-bc2c-70fc9cc7398b","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e8dc7a9d-c6a8-4295-86d5-0f675abd17c3","path":"sprites/ibtSa3_spr_act3figmentsR/ibtSa3_spr_act3figmentsR.yy",},},},"Disabled":false,"id":"a50c5197-9b02-4516-a53a-c7bbc4e55397","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 615,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 262,
}