{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "sqcs_0_2_6_spr_phead",
  "bbox_bottom": 174,
  "bbox_left": 249,
  "bbox_right": 445,
  "bbox_top": 15,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b10108fb-c2be-40e7-a27e-45805ea47c4c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"235a409e-31a3-4790-83b9-aac8213220dc",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6c341020-365f-4ac1-8b3d-7c3b7f04ce80",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"8c394178-fd3a-44b3-b773-9d24c668c944","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "sqcs_0_2_6_spr_phead",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 0.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b10108fb-c2be-40e7-a27e-45805ea47c4c","path":"sprites/sqcs_0_2_6_spr_phead/sqcs_0_2_6_spr_phead.yy",},},},"Disabled":false,"id":"95d9a8d4-29be-4a5d-b7b9-687e111100b3","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"235a409e-31a3-4790-83b9-aac8213220dc","path":"sprites/sqcs_0_2_6_spr_phead/sqcs_0_2_6_spr_phead.yy",},},},"Disabled":false,"id":"f977c3e1-90b9-4c7b-9823-8fee0948d79b","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6c341020-365f-4ac1-8b3d-7c3b7f04ce80","path":"sprites/sqcs_0_2_6_spr_phead/sqcs_0_2_6_spr_phead.yy",},},},"Disabled":false,"id":"82d826b8-257e-4329-be36-227cfcf245da","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 240,
    "yorigin": 135,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}