{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf1_spr_player_left",
  "bbox_bottom": 62,
  "bbox_left": 0,
  "bbox_right": 28,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b32dbe11-10a6-470e-a2f8-2510459c5ea8",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b22d909b-e2e2-4e64-b8cc-5352e36bad1e",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9329de7d-aae6-4be4-82eb-c2ba85335037",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9c7b33d5-861d-41b3-af83-33e94697b9e9",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 63,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"67c9b347-53fd-4d28-93ba-31ab398626da","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf1_spr_player_left",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b32dbe11-10a6-470e-a2f8-2510459c5ea8","path":"sprites/mf1_spr_player_left/mf1_spr_player_left.yy",},},},"Disabled":false,"id":"6b931e0e-0738-4191-be23-e722ae7d2292","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b22d909b-e2e2-4e64-b8cc-5352e36bad1e","path":"sprites/mf1_spr_player_left/mf1_spr_player_left.yy",},},},"Disabled":false,"id":"c14ac0da-84d1-431b-acfc-ac02bc380e6e","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9329de7d-aae6-4be4-82eb-c2ba85335037","path":"sprites/mf1_spr_player_left/mf1_spr_player_left.yy",},},},"Disabled":false,"id":"0358881d-4760-4f45-a51e-fa2a52744ff1","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9c7b33d5-861d-41b3-af83-33e94697b9e9","path":"sprites/mf1_spr_player_left/mf1_spr_player_left.yy",},},},"Disabled":false,"id":"94280fd0-57a8-47ce-bc7a-23c2a9b2c738","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 10,
    "yorigin": 62,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 29,
}