{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf0_spr_hand",
  "bbox_bottom": 175,
  "bbox_left": 147,
  "bbox_right": 351,
  "bbox_top": 20,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"713dfaff-6ede-414e-a8c8-d2218c2fd70e",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"b9c47bb7-1e08-4233-bdfa-08a2c7463531",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8a709ded-4879-4ab5-89bd-acdfeff0a5b0",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 400,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"8ffb8b93-4fdb-4990-a704-8abcd84d9426","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf0_spr_hand",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"713dfaff-6ede-414e-a8c8-d2218c2fd70e","path":"sprites/mf0_spr_hand/mf0_spr_hand.yy",},},},"Disabled":false,"id":"ed3c4453-db8e-478c-867f-29a7e762284d","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"b9c47bb7-1e08-4233-bdfa-08a2c7463531","path":"sprites/mf0_spr_hand/mf0_spr_hand.yy",},},},"Disabled":false,"id":"88520adb-b7e2-40a6-8455-f4d19d7a672f","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8a709ded-4879-4ab5-89bd-acdfeff0a5b0","path":"sprites/mf0_spr_hand/mf0_spr_hand.yy",},},},"Disabled":false,"id":"2732a8a9-a057-4718-9287-a358ece013ff","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 300,
    "yorigin": 200,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 600,
}