scr_collision_init();
scr_playersounds_init();
mainPlayerCharacter = UnknownEnum.Value_0;
character = mainPlayerCharacter;
previousCharacter = character;
breakdanceBuffer = 0;
breakdanceSpeed = 0;
cottonJumped = 0;
coyoteTime = 0;
stepBuffer = 0;
inBackgroundLayer = false;
upsideDownJump = false;
terminalVelocity = 20;
slideHsp = 0;
secretArray = [];
oldComboTitle = 0;
kungBuffer = 0;
blueAfterimage = 0;
machAfterimage = 0;
myPalettes = [];
new_palette("Classic", 16777215, 13150344);
new_palette("Sugar", 8441896, 6066975);
new_palette("Gremlin", 8446200, 1607896);
new_palette("Golden", 1489391, 25527, 1489391, 25527, 25527, 1489391);
new_palette("Purple", 16273560, 16273560);
new_palette("Cream n' Chips", spr_pattern0);
new_palette("Valiant Hero", spr_pattern1);
new_palette("Dead Man's Treats", spr_pattern2);
new_palette("Candy Cane", spr_pattern3);
new_palette("Sweet Apple", spr_pattern4);
new_palette("Space Cream", spr_pattern5);
new_palette("Sourness", spr_pattern6);
new_palette("Neapolitan", spr_pattern7);
new_palette("Cookie Cutter", spr_pattern8);
new_palette("MissingTexture", spr_pattern9);
new_palette("Solid", spr_pattern10);
new_palette("Chocoa", spr_pattern11);
new_palette("Cotton Candy", spr_pattern12);
comboTitle = -4;
scr_initinput();
scr_getinput();
frozenState = 0;
frozenSpriteIndex = spr_file2;
frozenImageIndex = 0;
frozenImageSpeed = 0.35;
frozenMoveSpeed = 0;
frozenGrav = 0.35;
frozenSmash = 0;
frozenHsp = 0;
frozenVsp = 0;
frozenJumpBuffer = 0;

for (var i = 0; i < 11; i++)
    frozenAlarm[i] = -1;

costumeBlock = -4;
costumeBlockDetails = 0;
angle = 0;
dummyBlock = -4;
bombID = -4;
angryCloudID = -4;
shakeTime = 3;
breezeCooldown = 25;
secretPortal = false;
isInSecretPortal = false;
global.DialogMessage = ds_queue_create();
chuckCooldown = 120;
inputBuffer = 0;
global.coneblock = false;
scale = 1;
sJumpCanDoubleJump = true;
fireTrailBuffer = 0;
playComboVariable = -4;
resetMusic = false;
dashpadBuffer = 0;
heatAfterEffectID = -4;
superTauntBuffer = 0;
superTauntCharged = false;
vertical = false;
verticalOffset = 0;
stateName = "";
groundpoundEffect = -4;
dashCloudID = -4;
machFourMode = false;
global.SaveRoom = ds_list_create();
grav = 0.5;
hsp = 0;
vsp = 0;
xscale = 1;
yscale = 1;
faceHurt = false;
steppy = false;
grabClimbBuffer = 0;
crouchSlipBuffer = 0;
crouchSlipAntiBuffer = 0;
depth = -99;
movespeed = 19;
jumpStop = false;
visible = true;
inhalingEnemy = false;
state = UnknownEnum.Value_2;
jumpAnim = true;
landAnim = false;
machSlideAnim = false;
crouchAnim = true;
gumbobPropellerFuelMax = 35;
gumbobPropellerFuel = gumbobPropellerFuelMax;
gumbobRollBounceBuff = 0;
gumbobBounceCounter = 0;
gumbobWallBounceBuff = 0;
gumbobDashTimer = 0;
gumbobDashAfterImageBuff = 0;
gumbobHitWall = false;
hurted = false;
canRebound = false;
machTwo = 0;
inputBufferSlap = 0;
playerX = x;
inputBufferJump = 8;
inputBufferSecondJump = 8;
inputBufferHighJump = 8;
superGrabX = 0;
superGrabY = 0;
targetRoom = 0;
flash = false;
toxicGasTimeMax = time_in_frames(0, 5);
toxicGasTime = toxicGasTimeMax;
showToxicTimerMax = time_in_frames(0, 2);
showToxicTimer = 0;
parryId = -4;
global.MallowFollow = false;
global.CrackFollow = false;
global.ChocoFollow = false;
global.WormFollow = false;
global.CandyFollow = false;
global.Collect = 0;
global.PokerChips = 0;
global.Treasure = false;
global.Combo = 0;
global.ComboScore = 0;
global.HighestCombo = 0;
global.ComboTime = 0;
global.ToppinTotal = 1;
global.ComboFreeze = 0;
global.ComboLost = false;
global.BaddieRoom = ds_list_create();
global.EscapeRoom = ds_list_create();
keyParticles = false;
idle = 0;
grounded = true;
groundedSlope = false;
machPunchAnim = false;
punch = false;
instakillmove = false;
windingAnim = 0;
ladderBuffer = 0;
bushDetection = 0;
idleAnim = 0;
momemtum = false;
cutscene = false;
grabbing = false;
dir = xscale;
dir2 = yscale;
shotgunAnim = false;
fallingAnimation = 0;
bombPepTimer = 100;
suplexMove = false;
anger = 0;
angry = false;
baddieGrabbedID = -4;
scr_characterSprite();
paletteSelect = 0;
global.panic = 0;
verticalMovespeed = 0;
tauntTimer = 20;
scr_taunt_storeVariables();
swingDingBuffer = 0;
lastMove = 0;
targetDoor = "A";
roomStartX = xstart;
roomStartY = ystart;
hallway = false;
box = false;
kungTime = 0;
global.Cane = false;
freeFallSmash = 0;
bounceSpeed = 0;
bounced = false;
groundedCot = false;
sourBuddies = ds_list_create();
sourBuddiesTimer = 60;
surfaceWidth = 2;
surfaceHeight = 10;
surfacePallete = -1;

if (!surface_exists(surfacePallete))
    surfacePallete = surface_create(surfaceWidth, surfaceHeight);

customSavedPalette = 1;
characters = "Pizzelle";
colorHeight = 8;
paletteWave = false;
customPalette = false;
inhaling = 0;
inhaleStrength = 0;
freeFallSmash = 0;
draw_angle = 0;
slopeAngle = 0;
jumpedOnce = false;
doubleJumped = false;
tripleJumped = false;
charged = false;
headless = false;
substate = 0;
vampireBlood = 0;
kungAirCount = false;
kungAirTime = 0;
seacreamStickBuffer = 0;
hp = 6;
ufoTimer = 0;
bumpedWallOrFloor = false;
bumpedCeiling = false;
bumpCounter = 0;
fire_afterimagetimer = 0;
u_mask = shader_get_uniform(shd_pattern, "u_MaskColour");
u_spr = shader_get_uniform(shd_pattern, "u_SprRect");
u_pat = shader_get_uniform(shd_pattern, "u_PatRect");
u_texel = shader_get_uniform(shd_pattern, "u_TexelScl");
u_offset = shader_get_uniform(shd_pattern, "u_SprOffset");
global.rocketLauncher = false;
global.tempRocketLauncher = false;
