{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms17_spr_winscreen",
  "bbox_bottom": 204,
  "bbox_left": 0,
  "bbox_right": 303,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"0b68354f-98e3-45fc-b9c1-7dc4985387a2",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"7f9ce091-b489-4999-ad8e-de41a6adf92c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"23bd957c-ab24-491b-baad-1b6cb826e705",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 205,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"37876100-2276-4e6b-882c-b5281defe0b7","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms17_spr_winscreen",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"0b68354f-98e3-45fc-b9c1-7dc4985387a2","path":"sprites/ms17_spr_winscreen/ms17_spr_winscreen.yy",},},},"Disabled":false,"id":"8461d523-81a8-4ec5-8a77-697b2c91c670","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"7f9ce091-b489-4999-ad8e-de41a6adf92c","path":"sprites/ms17_spr_winscreen/ms17_spr_winscreen.yy",},},},"Disabled":false,"id":"8df37130-37c5-44e8-a2f2-6a663be9d81a","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"23bd957c-ab24-491b-baad-1b6cb826e705","path":"sprites/ms17_spr_winscreen/ms17_spr_winscreen.yy",},},},"Disabled":false,"id":"a2e2c8a3-10e7-4f5b-b095-9a6eafc560d7","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 152,
    "yorigin": 102,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 304,
}