{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf1_spr_player_upleft",
  "bbox_bottom": 58,
  "bbox_left": 0,
  "bbox_right": 38,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"efefd94f-a7ca-414f-9800-d481bcdf8d69",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c077196d-9cad-49f7-a6a4-6d69a4397994",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"31ee4d3b-c496-451f-afc0-698d7bfe4eb5",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5862772a-0519-4d80-abef-ac0a085e6ca4",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 60,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"850add47-d8a9-4b13-9005-17667b506118","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf1_spr_player_upleft",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"efefd94f-a7ca-414f-9800-d481bcdf8d69","path":"sprites/mf1_spr_player_upleft/mf1_spr_player_upleft.yy",},},},"Disabled":false,"id":"109fc10b-340c-435f-800b-82732cc3fae0","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c077196d-9cad-49f7-a6a4-6d69a4397994","path":"sprites/mf1_spr_player_upleft/mf1_spr_player_upleft.yy",},},},"Disabled":false,"id":"43a86483-df7b-49ee-bddb-51dd2dce201e","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"31ee4d3b-c496-451f-afc0-698d7bfe4eb5","path":"sprites/mf1_spr_player_upleft/mf1_spr_player_upleft.yy",},},},"Disabled":false,"id":"2d9afbe2-89d2-4d0a-818f-c4ef16af5113","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5862772a-0519-4d80-abef-ac0a085e6ca4","path":"sprites/mf1_spr_player_upleft/mf1_spr_player_upleft.yy",},},},"Disabled":false,"id":"3e11d280-8b53-4f92-8f0f-fc3ec6e7f47d","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 22,
    "yorigin": 56,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 39,
}