{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms8_spr_hand",
  "bbox_bottom": 41,
  "bbox_left": 0,
  "bbox_right": 45,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c821425c-e943-440c-b2c3-383194a7408c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"874e4ba1-c5b2-4a21-9741-6886a46121ab",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f0e7a924-f66d-4d81-9f76-9678c3d735e7",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 42,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"7e869fdb-7a58-4fcf-89fa-aee8d29a5228","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms8_spr_hand",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c821425c-e943-440c-b2c3-383194a7408c","path":"sprites/ms8_spr_hand/ms8_spr_hand.yy",},},},"Disabled":false,"id":"aa33dac5-5786-482a-887c-a67ee1c49e46","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"874e4ba1-c5b2-4a21-9741-6886a46121ab","path":"sprites/ms8_spr_hand/ms8_spr_hand.yy",},},},"Disabled":false,"id":"845c9d54-fc63-4e79-8b51-47b4814ce109","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f0e7a924-f66d-4d81-9f76-9678c3d735e7","path":"sprites/ms8_spr_hand/ms8_spr_hand.yy",},},},"Disabled":false,"id":"4a66578b-1df2-44a6-94f6-c385aa6e143c","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 23,
    "yorigin": 21,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 46,
}