{
  "resourceType": "GMSequence",
  "resourceVersion": "1.4",
  "name": "seq_bridget_phone",
  "autoRecord": true,
  "backdropHeight": 768,
  "backdropImageOpacity": 0.5,
  "backdropImagePath": "",
  "backdropWidth": 1366,
  "backdropXOffset": 0.0,
  "backdropYOffset": 0.0,
  "events": {
    "resourceType": "KeyframeStore<MessageEventKeyframe>",
    "resourceVersion": "1.0",
    "Keyframes": [],
  },
  "eventStubScript": null,
  "eventToFunction": {},
  "length": 210.0,
  "lockOrigin": false,
  "moments": {
    "resourceType": "KeyframeStore<MomentsEventKeyframe>",
    "resourceVersion": "1.0",
    "Keyframes": [],
  },
  "parent": {
    "name": "Sequences",
    "path": "folders/Sequences.yy",
  },
  "playback": 0,
  "playbackSpeed": 60.0,
  "playbackSpeedType": 0,
  "showBackdrop": true,
  "showBackdropImage": false,
  "spriteId": null,
  "timeUnits": 1,
  "tracks": [
    {"resourceType":"GMAudioTrack","resourceVersion":"1.1","name":"snd_blackknives_spacecat","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AudioKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AudioKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AudioKeyframe","resourceVersion":"1.0","Id":{"name":"snd_blackknives_spacecat","path":"sounds/snd_blackknives_spacecat/snd_blackknives_spacecat.yy",},"Mode":0,},},"Disabled":false,"id":"56c2f5cb-2f77-4cdf-bdd0-307a998e3a52","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":4278232575,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"d335d49c-ddd2-4dd3-80db-d3a0a70685cb","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278232575,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"1723060e-a31d-4def-8ce9-7a93d7d743ba","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":4278232575,"tracks":[],"traits":0,},
      ],"traits":0,},
    {"resourceType":"GMClipMaskTrack","resourceVersion":"1.0","name":"variable","builtinName":11,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"modifiers":[],"trackColour":4286578816,"tracks":[
        {"resourceType":"GMClipMask_Mask","resourceVersion":"1.0","name":"mask","builtinName":12,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"modifiers":[],"trackColour":4286578816,"tracks":[
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_bridget_phone_maskfull","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_bridget_phone_maskfull","path":"sprites/spr_cutscene_blackknives_bridget_phone_maskfull/spr_cutscene_blackknives_bridget_phone_maskfull.yy",},},},"Disabled":false,"id":"e5af2451-0545-4450-9013-e61030b2fc2d","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"5f0e172e-283c-4e0b-87b4-93c92d99df54","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-643.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-410.0,},},"Disabled":false,"id":"2a926807-8785-4202-ba9c-df62fbdba7e9","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"bd095eea-6136-4970-95a8-60680dcc1594","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"69a197d8-0870-460b-8e7a-9a74a3c7cf61","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
          ],"traits":0,},
        {"resourceType":"GMClipMask_Subject","resourceVersion":"1.0","name":"subject","builtinName":13,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"modifiers":[],"trackColour":4286578816,"tracks":[
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_ui","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_ui","path":"sprites/spr_cutscene_blackknives_video_cat_ui/spr_cutscene_blackknives_video_cat_ui.yy",},},},"Disabled":false,"id":"80ce7775-a527-449a-a414-21f50b6d014f","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"image_index","builtinName":18,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"60c1a7a0-6bed-4c3e-b332-f3b14b26b028","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"image_speed","builtinName":17,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"eeca2f08-004f-490b-a7e0-6d2960315f20","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"45aebe74-38af-4ef6-9720-531789ff6e05","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-329.47998,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":235.0,},},"Disabled":false,"id":"91f8e182-30ce-4178-bb51-6597abf43c0c","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"dd6154ed-398f-4977-9409-582ced94dc9a","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"78f303a3-4635-4fef-9f8b-5812a24ca113","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_ui","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_ui","path":"sprites/spr_cutscene_blackknives_video_cat_ui/spr_cutscene_blackknives_video_cat_ui.yy",},},},"Disabled":false,"id":"92b2765a-5172-45f3-8639-b5f36d5be792","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"image_index","builtinName":18,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"image_speed","builtinName":17,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"9d08acbd-690b-4a6a-a301-caf571d45753","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-329.47998,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":235.0,},},"Disabled":false,"id":"935d9c6b-dabd-4920-8730-8e1dacd55cd0","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"59df2570-7e07-4f2e-b290-1dab9a6fd5f1","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"1492e512-54fd-4c8b-a42e-028e0c462a1d","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_follow","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_follow","path":"sprites/spr_cutscene_blackknives_video_cat_follow/spr_cutscene_blackknives_video_cat_follow.yy",},},},"Disabled":false,"id":"7a62ad6a-b2ac-4ad1-a00d-90d82acd458b","IsCreationKey":false,"Key":143.0,"Length":60.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMColourTrack","resourceVersion":"1.0","name":"blend_multiply","builtinName":10,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<ColourKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<ColourKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"ColourKeyframe","resourceVersion":"1.0","AnimCurveId":null,"Colour":4294967295,"EmbeddedAnimCurve":null,},},"Disabled":false,"id":"08dc6ba3-5163-4164-8092-c7cec968e0b9","IsCreationKey":false,"Key":188.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<ColourKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"ColourKeyframe","resourceVersion":"1.0","AnimCurveId":null,"Colour":16777215,"EmbeddedAnimCurve":null,},},"Disabled":false,"id":"028897c3-ffea-4552-9f2b-35bbeaad680f","IsCreationKey":false,"Key":194.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"f912f36c-ac94-4d78-8634-666978016692","IsCreationKey":false,"Key":143.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-346.97998,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":200.0,},},"Disabled":false,"id":"0af61ba2-e35a-432b-bc1c-8e22ef636507","IsCreationKey":false,"Key":143.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"441e90d8-5c9e-47a0-915f-dfe3e0e3cf3b","IsCreationKey":false,"Key":143.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"fa52c89f-da58-41cb-9da9-69e1f328f330","IsCreationKey":false,"Key":143.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":2.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":2.0,},},"Disabled":false,"id":"b2133f46-7f0c-430e-b20e-ef6480ee31fa","IsCreationKey":false,"Key":143.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.2,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.2,},},"Disabled":false,"id":"56ecb189-600b-4720-8b74-a4b5f0ffee94","IsCreationKey":false,"Key":145.68942,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.95,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.95,},},"Disabled":false,"id":"ea37d7dd-cf8b-42ef-82a3-bad46cedee61","IsCreationKey":false,"Key":194.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_like","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_like","path":"sprites/spr_cutscene_blackknives_video_cat_like/spr_cutscene_blackknives_video_cat_like.yy",},},},"Disabled":false,"id":"4bcf1bf2-289b-4c02-b7ec-8da72f61b9e0","IsCreationKey":false,"Key":83.0,"Length":60.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMColourTrack","resourceVersion":"1.0","name":"blend_multiply","builtinName":10,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<ColourKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<ColourKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"ColourKeyframe","resourceVersion":"1.0","AnimCurveId":null,"Colour":4294967295,"EmbeddedAnimCurve":null,},},"Disabled":false,"id":"a993cc1f-764d-46cf-b4f6-5935e3734f94","IsCreationKey":false,"Key":130.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<ColourKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"ColourKeyframe","resourceVersion":"1.0","AnimCurveId":null,"Colour":16777215,"EmbeddedAnimCurve":null,},},"Disabled":false,"id":"36c2ba30-f478-4578-987a-fa2a44b2d6af","IsCreationKey":false,"Key":136.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"f028c726-b079-461b-99b9-979f3fd3a699","IsCreationKey":false,"Key":83.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-360.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":206.63,},},"Disabled":false,"id":"4f715068-3015-4732-bef4-779a9131eaf4","IsCreationKey":false,"Key":83.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"db8ec1e6-749b-44c9-b7b0-49b545a5daae","IsCreationKey":false,"Key":83.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"5fc6bfff-aa18-466d-86a3-1bb48beb8c23","IsCreationKey":false,"Key":83.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":2.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":2.0,},},"Disabled":false,"id":"e729f585-0a99-41d7-a94f-05bbde6e9874","IsCreationKey":false,"Key":83.31058,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.2,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.2,},},"Disabled":false,"id":"786abf8b-b3ce-4d20-85d0-4b91b1f1659b","IsCreationKey":false,"Key":86.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"cf3fc546-a14e-4c44-ba5a-b5b88654dbc4","IsCreationKey":false,"Key":136.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_wave","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_wave","path":"sprites/spr_cutscene_blackknives_video_cat_wave/spr_cutscene_blackknives_video_cat_wave.yy",},},},"Disabled":false,"id":"45b8ee95-5e10-4d00-a8c0-bfcd30fcee4d","IsCreationKey":false,"Key":102.0,"Length":35.0,"Stretch":false,},
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_wave","path":"sprites/spr_cutscene_blackknives_video_cat_wave/spr_cutscene_blackknives_video_cat_wave.yy",},},},"Disabled":false,"id":"b794f2e4-f181-4183-b837-3813d145e9a4","IsCreationKey":false,"Key":197.0,"Length":35.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"625569b3-11f0-4f18-90f5-51f4b4a7d72e","IsCreationKey":false,"Key":102.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-46.37,},"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-369.48,},},"Disabled":false,"id":"c37c051d-b8ef-4ae9-a428-288de9e437b1","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"274649a6-444e-49f3-b47d-ad018bd9e8e4","IsCreationKey":false,"Key":102.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"eed99cf4-3b27-4d5a-9ee2-f058c46cfcb7","IsCreationKey":false,"Key":102.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_look","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_look","path":"sprites/spr_cutscene_blackknives_video_cat_look/spr_cutscene_blackknives_video_cat_look.yy",},},},"Disabled":false,"id":"d8cb1b5c-136b-433f-852e-34c369497669","IsCreationKey":false,"Key":34.0,"Length":34.0,"Stretch":false,},
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_look","path":"sprites/spr_cutscene_blackknives_video_cat_look/spr_cutscene_blackknives_video_cat_look.yy",},},},"Disabled":false,"id":"ed24a1eb-5e5d-4333-9b12-d27322e3d113","IsCreationKey":false,"Key":91.0,"Length":11.0,"Stretch":false,},
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_look","path":"sprites/spr_cutscene_blackknives_video_cat_look/spr_cutscene_blackknives_video_cat_look.yy",},},},"Disabled":false,"id":"d0bfb1b5-10b0-4d30-8c30-1b1721cb18c9","IsCreationKey":false,"Key":156.0,"Length":41.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"086e0de3-c3d4-45b3-9cf2-26345d9c9eb6","IsCreationKey":false,"Key":34.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-46.37,},"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-369.47595,},},"Disabled":false,"id":"0368bcbd-b5ec-449a-8869-1c7d8f9c00ec","IsCreationKey":false,"Key":34.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"4c27df30-a515-4f9d-bc89-8f8bbbebc8f2","IsCreationKey":false,"Key":34.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"021e1564-d4ea-43ab-bc14-5daddcf256bc","IsCreationKey":false,"Key":34.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_video_cat_idle","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_idle","path":"sprites/spr_cutscene_blackknives_video_cat_idle/spr_cutscene_blackknives_video_cat_idle.yy",},},},"Disabled":false,"id":"67e48e35-b74e-4ec9-81e4-930141a632af","IsCreationKey":false,"Key":0.0,"Length":34.0,"Stretch":false,},
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_idle","path":"sprites/spr_cutscene_blackknives_video_cat_idle/spr_cutscene_blackknives_video_cat_idle.yy",},},},"Disabled":false,"id":"8fb090e9-c695-4a3c-a14a-bfc78419f48c","IsCreationKey":false,"Key":68.0,"Length":23.0,"Stretch":false,},
                  {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_video_cat_idle","path":"sprites/spr_cutscene_blackknives_video_cat_idle/spr_cutscene_blackknives_video_cat_idle.yy",},},},"Disabled":false,"id":"9d7f1a66-1c86-4499-87a5-277a21a3d8b3","IsCreationKey":false,"Key":137.0,"Length":19.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"image_speed","builtinName":17,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"c6a5a583-9a75-409d-a931-e5163a46b2a3","IsCreationKey":false,"Key":22.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.5,},},"Disabled":false,"id":"fede9536-abba-4931-a392-5e9862decca9","IsCreationKey":false,"Key":23.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.5,},},"Disabled":false,"id":"82c12bd2-9462-4fca-bc6e-978d9c46537e","IsCreationKey":false,"Key":68.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"a1792f6e-0176-46ae-979f-24b9d7041a1a","IsCreationKey":false,"Key":69.0,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.5,},},"Disabled":false,"id":"8ea29164-9ec1-4e9d-8e8b-0cc61713f510","IsCreationKey":false,"Key":137.31917,"Length":1.0,"Stretch":false,},
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":2.0,},},"Disabled":false,"id":"30f4ec4b-8806-428d-8c31-3c8b1f088cae","IsCreationKey":false,"Key":138.31917,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"463539f4-e7c4-4846-847a-043f3651bf43","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-369.47595,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-46.371155,},},"Disabled":false,"id":"2ab01df9-3204-474a-b0c0-94aba27302c4","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"40795b57-cd11-4f83-89a2-fdd679b92f9e","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"12f0f6e4-f7e9-4c68-828e-08a25245ddb6","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
            {"resourceType":"GMInstanceTrack","resourceVersion":"1.0","name":"obj_cutscene_blackknives_cat_bg","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetInstanceKeyframe>","resourceVersion":"1.0","Keyframes":[
                  {"resourceType":"Keyframe<AssetInstanceKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetInstanceKeyframe","resourceVersion":"1.0","Id":{"name":"obj_cutscene_blackknives_cat_bg","path":"objects/obj_cutscene_blackknives_cat_bg/obj_cutscene_blackknives_cat_bg.yy",},},},"Disabled":false,"id":"9fe8ba4a-4c47-47b7-9c99-8c31fd5b9867","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
                ],},"modifiers":[],"trackColour":4286578816,"tracks":[
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"af7f1f62-8f11-4c29-afa1-d312d47dbe3b","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-249.97595,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-107.0,},},"Disabled":false,"id":"6405d23a-b2c5-422b-8ffe-0e6b4fa87fdf","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"35e1ee85-8040-4e4b-a17d-0b2d23f0b20f","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
                {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
                      {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"74ab38cd-56d5-434e-852b-da3de2302a54","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
                    ],},"modifiers":[],"trackColour":4286578816,"tracks":[],"traits":0,},
              ],"traits":0,},
          ],"traits":0,},
      ],"traits":0,},
    {"resourceType":"GMGraphicTrack","resourceVersion":"1.0","name":"spr_cutscene_blackknives_bridget_phone","builtinName":0,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<AssetSpriteKeyframe>","resourceVersion":"1.0","Keyframes":[
          {"resourceType":"Keyframe<AssetSpriteKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"AssetSpriteKeyframe","resourceVersion":"1.0","Id":{"name":"spr_cutscene_blackknives_bridget_phone","path":"sprites/spr_cutscene_blackknives_bridget_phone/spr_cutscene_blackknives_bridget_phone.yy",},},},"Disabled":false,"id":"7d1aadc2-cf6e-4480-9dd8-4ecf8f26e29a","IsCreationKey":false,"Key":0.0,"Length":210.0,"Stretch":false,},
        ],},"modifiers":[],"trackColour":16711680,"tracks":[
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"origin","builtinName":16,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"311c8627-ac9b-407d-ac1e-f87acc872d3a","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":16711680,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"position","builtinName":14,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-960.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":-540.0,},},"Disabled":false,"id":"ea8c5a6a-d7b2-4d0f-9e47-217760985d3d","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":16711680,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"rotation","builtinName":8,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":0.0,},},"Disabled":false,"id":"c2bdc062-ee51-42c2-a3b2-f05b2df9d768","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":16711680,"tracks":[],"traits":0,},
        {"resourceType":"GMRealTrack","resourceVersion":"1.0","name":"scale","builtinName":15,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":true,"keyframes":{"resourceType":"KeyframeStore<RealKeyframe>","resourceVersion":"1.0","Keyframes":[
              {"resourceType":"Keyframe<RealKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},"1":{"resourceType":"RealKeyframe","resourceVersion":"1.0","AnimCurveId":null,"EmbeddedAnimCurve":null,"RealValue":1.0,},},"Disabled":false,"id":"b47bcdf4-a8ce-4f5c-a6d6-2674e0f35d68","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            ],},"modifiers":[],"trackColour":16711680,"tracks":[],"traits":0,},
      ],"traits":0,},
  ],
  "visibleRange": null,
  "volume": 1.0,
  "xorigin": 0,
  "yorigin": 0,
}