{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtSa3_spr_boss",
  "bbox_bottom": 191,
  "bbox_left": 26,
  "bbox_right": 453,
  "bbox_top": 55,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"21c676ef-ad56-41ed-88f6-5a24337110b7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"45cef4f3-6b35-4c1d-aa8e-eb47ba2f76bb",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e5107758-e815-4bb4-b500-1e5427e0e2e3",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"593b9258-6032-4fea-b301-8c3cbbcda96f",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 833,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"1801188a-46af-48b4-9db5-f3851aa0ea46","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 7,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtSa3_spr_boss",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 5.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"21c676ef-ad56-41ed-88f6-5a24337110b7","path":"sprites/ibtSa3_spr_boss/ibtSa3_spr_boss.yy",},},},"Disabled":false,"id":"5ff8074d-8e56-4904-8449-e4e30d4c5032","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"45cef4f3-6b35-4c1d-aa8e-eb47ba2f76bb","path":"sprites/ibtSa3_spr_boss/ibtSa3_spr_boss.yy",},},},"Disabled":false,"id":"0f275044-6ef9-479e-a997-6f204573144a","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e5107758-e815-4bb4-b500-1e5427e0e2e3","path":"sprites/ibtSa3_spr_boss/ibtSa3_spr_boss.yy",},},},"Disabled":false,"id":"1ff4c87e-1f4b-4578-9c0c-b7a4ff526494","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"593b9258-6032-4fea-b301-8c3cbbcda96f","path":"sprites/ibtSa3_spr_boss/ibtSa3_spr_boss.yy",},},},"Disabled":false,"id":"ca2ed917-2230-4f27-85d8-11ebd21c670d","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 240,
    "yorigin": 833,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}