{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms7_spr_dude",
  "bbox_bottom": 44,
  "bbox_left": 13,
  "bbox_right": 25,
  "bbox_top": 0,
  "bboxMode": 2,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e1d2976a-50cd-4b69-802d-1a60da9aa1c8",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"87651fbd-3813-43b2-bba0-d66fff94ea7c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"afa1c6d8-f4a5-49c3-9ad4-ff0867debdc2",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 45,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"adf6f5c5-8129-4fa7-9356-750f36e36c64","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms7_spr_dude",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e1d2976a-50cd-4b69-802d-1a60da9aa1c8","path":"sprites/ms7_spr_dude/ms7_spr_dude.yy",},},},"Disabled":false,"id":"703450e0-5a2b-4c98-8813-260a5017da36","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"87651fbd-3813-43b2-bba0-d66fff94ea7c","path":"sprites/ms7_spr_dude/ms7_spr_dude.yy",},},},"Disabled":false,"id":"d8196c59-848b-4f68-b943-16b8c06bafa7","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"afa1c6d8-f4a5-49c3-9ad4-ff0867debdc2","path":"sprites/ms7_spr_dude/ms7_spr_dude.yy",},},},"Disabled":false,"id":"4be62a36-0c03-4855-bec4-89d7eee274a3","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 20,
    "yorigin": 22,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 40,
}