shader = sha_heatwave;
uTime = shader_get_uniform(shader, "Time");
uTexel = shader_get_uniform(shader, "Texel");
uFreq = shader_get_uniform(shader, "uFreq");
uSize = shader_get_uniform(shader, "uSize");
time = 0;
surf = -4;
u_theta = shader_get_uniform(sha_hueshift, "u_theta");
hue = random_range(-1, 1);
