{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_mmui_hoverimg0_fill",
  "bbox_bottom": 269,
  "bbox_left": 252,
  "bbox_right": 479,
  "bbox_top": 24,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"46f6435b-b30f-44a2-849b-a51415097872",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"a5fb5332-55c6-473b-bb0a-b8421dc673b1",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"0381c58f-9e31-4889-b688-d68bc645806c",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"47c937f2-3078-4db8-ab36-2878115e390e","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_mmui_hoverimg0_fill",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"46f6435b-b30f-44a2-849b-a51415097872","path":"sprites/spr_mmui_hoverimg0_fill/spr_mmui_hoverimg0_fill.yy",},},},"Disabled":false,"id":"bb3ad973-faa5-41d4-a86b-a3ea03c45444","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"a5fb5332-55c6-473b-bb0a-b8421dc673b1","path":"sprites/spr_mmui_hoverimg0_fill/spr_mmui_hoverimg0_fill.yy",},},},"Disabled":false,"id":"c88fb78f-8961-4749-a300-10fbabd1b313","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"0381c58f-9e31-4889-b688-d68bc645806c","path":"sprites/spr_mmui_hoverimg0_fill/spr_mmui_hoverimg0_fill.yy",},},},"Disabled":false,"id":"67bcfbcc-98bc-4fbe-9029-6a19c38fa981","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}