{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms17_spr_lose_abb",
  "bbox_bottom": 205,
  "bbox_left": 0,
  "bbox_right": 128,
  "bbox_top": 23,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d658bfd0-e1ee-4499-940d-1e5dd3b7f8f7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"0155a1f8-47b7-4266-87bc-09e59c79da21",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"665e518b-98b7-4721-8146-94b57695ffaa",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 206,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"e1c3f64c-9920-406a-b782-d012c0c5cd32","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms17_spr_lose_abb",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 16.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d658bfd0-e1ee-4499-940d-1e5dd3b7f8f7","path":"sprites/ms17_spr_lose_abb/ms17_spr_lose_abb.yy",},},},"Disabled":false,"id":"779c064c-7c3b-43c9-81cd-8526745de667","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"0155a1f8-47b7-4266-87bc-09e59c79da21","path":"sprites/ms17_spr_lose_abb/ms17_spr_lose_abb.yy",},},},"Disabled":false,"id":"88d61072-592b-447a-850b-d8be7495ac64","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"665e518b-98b7-4721-8146-94b57695ffaa","path":"sprites/ms17_spr_lose_abb/ms17_spr_lose_abb.yy",},},},"Disabled":false,"id":"0ece09f2-5419-43b1-9b64-3d4846cc3b4e","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 111,
    "yorigin": 103,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 222,
}