{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "msboss_spr_portal_outline",
  "bbox_bottom": 69,
  "bbox_left": 0,
  "bbox_right": 168,
  "bbox_top": 0,
  "bboxMode": 1,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"1b2e8a92-73e9-4a34-b4a0-2e8069a3fa40",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"434336d1-50eb-4e0e-b839-9a3a0f7f563d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"664ec4d7-9f24-47ae-a9b0-426899a0876f",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 70,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"95e667dc-5aeb-411f-a274-abcec27841f2","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "msboss_spr_portal_outline",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 3.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"1b2e8a92-73e9-4a34-b4a0-2e8069a3fa40","path":"sprites/msboss_spr_portal_outline/msboss_spr_portal_outline.yy",},},},"Disabled":false,"id":"68f20d13-3881-44d3-af9a-c0570ec3ed81","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"434336d1-50eb-4e0e-b839-9a3a0f7f563d","path":"sprites/msboss_spr_portal_outline/msboss_spr_portal_outline.yy",},},},"Disabled":false,"id":"dc113f63-9f5e-4a6d-b3b4-c4188cdbd4cc","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"664ec4d7-9f24-47ae-a9b0-426899a0876f","path":"sprites/msboss_spr_portal_outline/msboss_spr_portal_outline.yy",},},},"Disabled":false,"id":"66e8ac33-7ad1-4333-9164-4c530271857b","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 84,
    "yorigin": 35,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 169,
}