testvariablenothing = false;
time = 0;
text_linemaxW = 1350;
draw_set_font(global.font_dialogue_outline);
blip = -4;
scr_dialogue_reset(splash_text, true);
name_percent = 0;
name_in = true;
ready = true;
text_spd_default = 0.6;
timer[0] = 60;
