{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms5_spr_face2",
  "bbox_bottom": 27,
  "bbox_left": 3,
  "bbox_right": 40,
  "bbox_top": 3,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"aa678c3f-7700-434a-9a6c-c8945285da13",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"70c5ebc1-6e56-45d4-add0-2dd15fb4e9e1",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"97f95a35-4119-4bba-bc1d-e02dd3ead6a6",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 31,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"4b06b4ec-0bcf-4bed-926c-5a61c4b31ee9","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms5_spr_face2",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 25.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"aa678c3f-7700-434a-9a6c-c8945285da13","path":"sprites/ms5_spr_face2/ms5_spr_face2.yy",},},},"Disabled":false,"id":"24515b4b-4a99-46a8-ad22-64738c1dbc25","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"70c5ebc1-6e56-45d4-add0-2dd15fb4e9e1","path":"sprites/ms5_spr_face2/ms5_spr_face2.yy",},},},"Disabled":false,"id":"4551de2d-d256-47c6-94fe-8ada85bf95aa","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"97f95a35-4119-4bba-bc1d-e02dd3ead6a6","path":"sprites/ms5_spr_face2/ms5_spr_face2.yy",},},},"Disabled":false,"id":"da272327-ca51-4771-a9de-f72ed1dd4215","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 21,
    "yorigin": 15,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 43,
}