{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mf3_spr_mouse",
  "bbox_bottom": 110,
  "bbox_left": 0,
  "bbox_right": 86,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8e82f4ed-f2a0-4fea-9871-94c614a5418f",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e1a1bb75-7d70-4120-a322-a6fe8e96bb51",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6f558368-5904-4c9f-a13e-dfb5f6cf4e66",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 180,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"1927e4a3-5499-47ec-bf63-3f052124f378","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mf3_spr_mouse",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 12.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8e82f4ed-f2a0-4fea-9871-94c614a5418f","path":"sprites/mf3_spr_mouse/mf3_spr_mouse.yy",},},},"Disabled":false,"id":"855ebc0b-8afe-4d26-89d6-80b1b558793b","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e1a1bb75-7d70-4120-a322-a6fe8e96bb51","path":"sprites/mf3_spr_mouse/mf3_spr_mouse.yy",},},},"Disabled":false,"id":"7341422f-192d-4370-b231-529530d55f5d","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6f558368-5904-4c9f-a13e-dfb5f6cf4e66","path":"sprites/mf3_spr_mouse/mf3_spr_mouse.yy",},},},"Disabled":false,"id":"6dcc2bab-7ab1-42de-95ec-cf02f1ca6d16","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 43,
    "yorigin": 90,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 87,
}