{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms8_spr_littleshit",
  "bbox_bottom": 69,
  "bbox_left": 0,
  "bbox_right": 99,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f4fd1d46-eb02-47f3-a9ee-ec9e88bf83c2",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"2399185d-171d-4e7c-b254-fec1fe044498",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"f68b8be4-7c2b-4af7-9b21-fb1c2197f68c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5fc8d6c8-bfbf-40a1-9a7e-7bb18543c8ba",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"19f4d7c8-509d-48dd-b7a7-2de494cf4e4c",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 70,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"7d6f97bd-f3a1-4866-9012-e245709fb00b","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms8_spr_littleshit",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 5.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 33.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f4fd1d46-eb02-47f3-a9ee-ec9e88bf83c2","path":"sprites/ms8_spr_littleshit/ms8_spr_littleshit.yy",},},},"Disabled":false,"id":"a14b14a0-cc91-4843-85e0-e8eca84d6a73","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"2399185d-171d-4e7c-b254-fec1fe044498","path":"sprites/ms8_spr_littleshit/ms8_spr_littleshit.yy",},},},"Disabled":false,"id":"7210fb99-be19-407a-aedc-c0ae968bb63b","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"f68b8be4-7c2b-4af7-9b21-fb1c2197f68c","path":"sprites/ms8_spr_littleshit/ms8_spr_littleshit.yy",},},},"Disabled":false,"id":"1c2e72c8-8884-49ac-b620-c20c6712caef","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5fc8d6c8-bfbf-40a1-9a7e-7bb18543c8ba","path":"sprites/ms8_spr_littleshit/ms8_spr_littleshit.yy",},},},"Disabled":false,"id":"ffb4d00d-f5d6-4861-bb5a-0d6cde108b9c","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"19f4d7c8-509d-48dd-b7a7-2de494cf4e4c","path":"sprites/ms8_spr_littleshit/ms8_spr_littleshit.yy",},},},"Disabled":false,"id":"1dbd9ee5-4e7b-458a-b06f-7b8aedb99de7","IsCreationKey":false,"Key":4.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 50,
    "yorigin": 35,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 100,
}