{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms10_spr_sparkle_mm",
  "bbox_bottom": 231,
  "bbox_left": 52,
  "bbox_right": 274,
  "bbox_top": 4,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e0a48890-0d45-4a92-89f6-6355efaca599",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"d786f0a7-a2c2-40cb-8956-799aefdc8d80",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"74f5d28a-7fdf-496e-b0ff-d2b88df20eb0",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 232,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"ca1db7fe-134a-4cc9-98d4-822ac195d5c0","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 7,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms10_spr_sparkle_mm",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 33.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e0a48890-0d45-4a92-89f6-6355efaca599","path":"sprites/ms10_spr_sparkle_mm/ms10_spr_sparkle_mm.yy",},},},"Disabled":false,"id":"7615ea98-13aa-4f70-9718-be532362ece7","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"d786f0a7-a2c2-40cb-8956-799aefdc8d80","path":"sprites/ms10_spr_sparkle_mm/ms10_spr_sparkle_mm.yy",},},},"Disabled":false,"id":"456ddd9d-becc-470f-a1a9-815cb2536a04","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"74f5d28a-7fdf-496e-b0ff-d2b88df20eb0","path":"sprites/ms10_spr_sparkle_mm/ms10_spr_sparkle_mm.yy",},},},"Disabled":false,"id":"0d0d96f4-920a-4707-a672-f606295be99e","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 162,
    "yorigin": 232,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 324,
}