get_cams(1);
shader_set(sha_heatwave);
shader_set_uniform_f(uTime, time);
shader_set_uniform_f(uFreq, 75);
shader_set_uniform_f(uSize, 3);
var tex = sprite_get_texture(spr_micro_pistol_bg, 0);
shader_set_uniform_f(uTexel, texture_get_texel_width(tex), texture_get_texel_height(tex));
draw_sprite(spr_micro_pistol_bg, 0, camx, camy);
shader_reset();
draw_sprite_ext(spr_micro_pistol_bg, 1, camx, camy, 1, 1, 0, c_white, heaven_alpha);
