{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ibtT_spr_tutoguytalk",
  "bbox_bottom": 136,
  "bbox_left": 346,
  "bbox_right": 468,
  "bbox_top": 21,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"13c16d2f-9173-4ffa-b6eb-31713ae74c07",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8b550f44-0201-4365-a09c-6c8c6acefb29",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"fa65d31d-7cbd-4765-ba88-6f243984b098",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6beb7d63-7083-4057-a6b7-f7c15e788d53",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 270,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"f5d1aada-fdfd-46d0-baf2-351e4320fefe","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ibtT_spr_tutoguytalk",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 5.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"13c16d2f-9173-4ffa-b6eb-31713ae74c07","path":"sprites/ibtT_spr_tutoguytalk/ibtT_spr_tutoguytalk.yy",},},},"Disabled":false,"id":"5ab1d2d6-ed22-4392-b70f-e6fedd0e6345","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8b550f44-0201-4365-a09c-6c8c6acefb29","path":"sprites/ibtT_spr_tutoguytalk/ibtT_spr_tutoguytalk.yy",},},},"Disabled":false,"id":"8ab6fe58-0e9b-4a59-990a-1498f280d589","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"fa65d31d-7cbd-4765-ba88-6f243984b098","path":"sprites/ibtT_spr_tutoguytalk/ibtT_spr_tutoguytalk.yy",},},},"Disabled":false,"id":"5ae3beda-1c52-49ac-94ca-ea8ffb2bd55a","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6beb7d63-7083-4057-a6b7-f7c15e788d53","path":"sprites/ibtT_spr_tutoguytalk/ibtT_spr_tutoguytalk.yy",},},},"Disabled":false,"id":"96126ea3-a7d1-4648-a0d9-53bf91cb108d","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 480,
}