HaveHit = 0;
WayWin = 0;
MusicP = 0;
F4toggle = true;
F4state = 1;
//window_set_fullscreen(true);
JC = false;
Tyme = 0;
Deaths = 0;
NoHit = "Disabled";
KeyT = 1;
MM_KeyTyme = 0;
audio_group_load(1);
audio_group_load(2);
PinkMode = 1;
Zoom = 1;
TargetZoom = Zoom;
ZoomDelay = 10;
PlayTest = false;
AllowPM = true;
PK = 0;
PC = 0;
pKey = 0;
PT = 0;
PistonMode = false;
Csound = snd_menumove;
Win_P = false;
setP = false;
Win_G = false;
setG = false;
Win_NoHit = false;
loadGame();
global.padconnected = -4;
