{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms3_spr_pinkpickup",
  "bbox_bottom": 61,
  "bbox_left": 0,
  "bbox_right": 76,
  "bbox_top": 0,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"991daf42-c069-402f-a99c-43949ad1c6cc",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"413cf8d2-9c78-4538-9f2c-a92dd3fbf928",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"34168583-545c-4585-a61b-44ffa5ee227b",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 62,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"eda7aaf8-be6b-4029-93d3-23e27104e238","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 9,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms3_spr_pinkpickup",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"991daf42-c069-402f-a99c-43949ad1c6cc","path":"sprites/ms3_spr_pinkpickup/ms3_spr_pinkpickup.yy",},},},"Disabled":false,"id":"31b3245a-3248-4af6-aa8e-44ce42a05e38","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"413cf8d2-9c78-4538-9f2c-a92dd3fbf928","path":"sprites/ms3_spr_pinkpickup/ms3_spr_pinkpickup.yy",},},},"Disabled":false,"id":"800798d2-07fc-4d03-8bcc-8461561ddbf7","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"34168583-545c-4585-a61b-44ffa5ee227b","path":"sprites/ms3_spr_pinkpickup/ms3_spr_pinkpickup.yy",},},},"Disabled":false,"id":"e24a1839-8f29-45d1-bf18-3f7661488e34","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 50,
    "yorigin": 4,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 77,
}