{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "spr_leaderboard_score_container",
  "bbox_bottom": 3,
  "bbox_left": 1,
  "bbox_right": 3,
  "bbox_top": 1,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"9b482e97-9e83-420b-8844-e51485bbf95b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"6ca9ec9c-9cdb-4484-b748-d79fdcd7ba6d",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"8d26c3d3-6692-42dc-b723-245783681df9",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"69b9f406-0458-4e79-9e5a-3b20343e4747",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 5,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"d8e6af1d-3a20-4f00-b858-d7155fb15154","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": {
    "resourceType": "GMNineSliceData",
    "resourceVersion": "1.0",
    "bottom": 2,
    "enabled": true,
    "guideColour": [
      4294902015,
      4294902015,
      4294902015,
      4294902015,
      4294902015,
    ],
    "highlightColour": 1728023040,
    "highlightStyle": 0,
    "left": 2,
    "right": 2,
    "tileMode": [
      0,
      0,
      0,
      0,
      0,
    ],
    "top": 2,
  },
  "origin": 0,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "spr_leaderboard_score_container",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"9b482e97-9e83-420b-8844-e51485bbf95b","path":"sprites/spr_leaderboard_score_container/spr_leaderboard_score_container.yy",},},},"Disabled":false,"id":"12170915-4694-4ff1-b27a-a6a8f25c2134","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"6ca9ec9c-9cdb-4484-b748-d79fdcd7ba6d","path":"sprites/spr_leaderboard_score_container/spr_leaderboard_score_container.yy",},},},"Disabled":false,"id":"f77a02cf-f955-4855-9471-f7123b2e161a","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"8d26c3d3-6692-42dc-b723-245783681df9","path":"sprites/spr_leaderboard_score_container/spr_leaderboard_score_container.yy",},},},"Disabled":false,"id":"c21125d3-c231-4e15-9ab7-54e9d9777382","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"69b9f406-0458-4e79-9e5a-3b20343e4747","path":"sprites/spr_leaderboard_score_container/spr_leaderboard_score_container.yy",},},},"Disabled":false,"id":"54db3c87-959c-44c4-b73d-c16e841b4e0c","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 0,
    "yorigin": 0,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 5,
}