{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "mt2_spr_vick_crazy",
  "bbox_bottom": 281,
  "bbox_left": 98,
  "bbox_right": 279,
  "bbox_top": 17,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"cf60039f-6ac1-46f6-8ab5-ab798b9dab77",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c43106a0-1209-4bcf-bcfa-66146cd8fd17",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"c0fc98df-00b7-4b83-889a-0cc8009dc97c",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 296,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"c1de482d-7b13-4d33-baa7-f5e099104210","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "mt2_spr_vick_crazy",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 25.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"cf60039f-6ac1-46f6-8ab5-ab798b9dab77","path":"sprites/mt2_spr_vick_crazy/mt2_spr_vick_crazy.yy",},},},"Disabled":false,"id":"488dd03b-5a81-4255-af09-ac9a7f9a4e77","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c43106a0-1209-4bcf-bcfa-66146cd8fd17","path":"sprites/mt2_spr_vick_crazy/mt2_spr_vick_crazy.yy",},},},"Disabled":false,"id":"565d8a7d-a4c5-42bd-8f07-96f34e5c6ec0","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"c0fc98df-00b7-4b83-889a-0cc8009dc97c","path":"sprites/mt2_spr_vick_crazy/mt2_spr_vick_crazy.yy",},},},"Disabled":false,"id":"7f5c173c-2325-4472-9f95-9b2098e6362d","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 144,
    "yorigin": 148,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 289,
}