{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms1_spr_ui_bottle",
  "bbox_bottom": 32,
  "bbox_left": 8,
  "bbox_right": 26,
  "bbox_top": 1,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"46fd93e0-aee4-44e8-8f71-75a7dc62b9f5",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"3ead1229-5c5f-4b21-ad28-b46a588b8fd6",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"5985b538-78a9-4db5-9e65-470b9768a184",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 35,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"02a10b40-46bd-43a4-a394-20589a6b687a","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 4,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms1_spr_ui_bottle",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 3.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"46fd93e0-aee4-44e8-8f71-75a7dc62b9f5","path":"sprites/ms1_spr_ui_bottle/ms1_spr_ui_bottle.yy",},},},"Disabled":false,"id":"12f68074-921d-4a9b-ba14-2d02e2bc28be","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"3ead1229-5c5f-4b21-ad28-b46a588b8fd6","path":"sprites/ms1_spr_ui_bottle/ms1_spr_ui_bottle.yy",},},},"Disabled":false,"id":"eb3beddf-cc05-4be3-94de-64e67fc0665c","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"5985b538-78a9-4db5-9e65-470b9768a184","path":"sprites/ms1_spr_ui_bottle/ms1_spr_ui_bottle.yy",},},},"Disabled":false,"id":"3a6db916-0393-4ad6-b195-1bbd035e83cb","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 17,
    "yorigin": 17,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 35,
}