{
  "resourceType": "GMSprite",
  "resourceVersion": "1.0",
  "name": "ms10_spr_guy_run",
  "bbox_bottom": 51,
  "bbox_left": 3,
  "bbox_right": 32,
  "bbox_top": 8,
  "bboxMode": 0,
  "collisionKind": 1,
  "collisionTolerance": 0,
  "DynamicTexturePage": false,
  "edgeFiltering": false,
  "For3D": false,
  "frames": [
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"e9e26f8d-ed84-4261-bf45-5c008db07b8b",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"239905e6-580b-43f6-a44d-7293c520a43c",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"619db625-af25-409e-8402-89bb8c357fc7",},
    {"resourceType":"GMSpriteFrame","resourceVersion":"1.1","name":"dcf174d6-0f64-4775-b351-6d881fa38eca",},
  ],
  "gridX": 0,
  "gridY": 0,
  "height": 52,
  "HTile": false,
  "layers": [
    {"resourceType":"GMImageLayer","resourceVersion":"1.0","name":"863e3be9-a155-4b64-b32b-12d86c91ffe9","blendMode":0,"displayName":"default","isLocked":false,"opacity":100.0,"visible":true,},
  ],
  "nineSlice": null,
  "origin": 7,
  "parent": {
    "name": "Sprites",
    "path": "folders/Sprites.yy",
  },
  "preMultiplyAlpha": false,
  "sequence": {
    "resourceType": "GMSequence",
    "resourceVersion": "1.4",
    "name": "ms10_spr_guy_run",
    "autoRecord": true,
    "backdropHeight": 768,
    "backdropImageOpacity": 0.5,
    "backdropImagePath": "",
    "backdropWidth": 1366,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "events": {"resourceType":"KeyframeStore<MessageEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "eventStubScript": null,
    "eventToFunction": {},
    "length": 4.0,
    "lockOrigin": false,
    "moments": {"resourceType":"KeyframeStore<MomentsEventKeyframe>","resourceVersion":"1.0","Keyframes":[],},
    "playback": 1,
    "playbackSpeed": 12.0,
    "playbackSpeedType": 0,
    "showBackdrop": true,
    "showBackdropImage": false,
    "timeUnits": 1,
    "tracks": [
      {"resourceType":"GMSpriteFramesTrack","resourceVersion":"1.0","name":"frames","builtinName":-1,"events":[],"inheritsTrackColour":true,"interpolation":1,"isCreationTrack":false,"keyframes":{"resourceType":"KeyframeStore<SpriteFrameKeyframe>","resourceVersion":"1.0","Keyframes":[
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"e9e26f8d-ed84-4261-bf45-5c008db07b8b","path":"sprites/ms10_spr_guy_run/ms10_spr_guy_run.yy",},},},"Disabled":false,"id":"bf334478-7852-40ae-8e52-f7d6ea31c076","IsCreationKey":false,"Key":0.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"239905e6-580b-43f6-a44d-7293c520a43c","path":"sprites/ms10_spr_guy_run/ms10_spr_guy_run.yy",},},},"Disabled":false,"id":"3506c87e-5de9-4b5b-9e99-4763e8046739","IsCreationKey":false,"Key":1.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"619db625-af25-409e-8402-89bb8c357fc7","path":"sprites/ms10_spr_guy_run/ms10_spr_guy_run.yy",},},},"Disabled":false,"id":"75eb57ea-12fe-4882-a0b5-f1f85b6f6df4","IsCreationKey":false,"Key":2.0,"Length":1.0,"Stretch":false,},
            {"resourceType":"Keyframe<SpriteFrameKeyframe>","resourceVersion":"1.0","Channels":{"0":{"resourceType":"SpriteFrameKeyframe","resourceVersion":"1.0","Id":{"name":"dcf174d6-0f64-4775-b351-6d881fa38eca","path":"sprites/ms10_spr_guy_run/ms10_spr_guy_run.yy",},},},"Disabled":false,"id":"154c56cd-64a6-4bb9-8889-06606cc2e1e1","IsCreationKey":false,"Key":3.0,"Length":1.0,"Stretch":false,},
          ],},"modifiers":[],"spriteId":null,"trackColour":0,"tracks":[],"traits":0,},
    ],
    "visibleRange": null,
    "volume": 1.0,
    "xorigin": 18,
    "yorigin": 52,
  },
  "swatchColours": null,
  "swfPrecision": 2.525,
  "textureGroupId": {
    "name": "default",
    "path": "texturegroups/default",
  },
  "type": 0,
  "VTile": false,
  "width": 36,
}